id,target,report,nlonPrediction
0,1,### OrientDB Version: 3.0.21,Not
1,1,### Java Version: 1.8.0_144,Not
2,1,### OS: windows 10,Not
4,1,## Expected behavior,NL
7,1,## Actual behavior,NL
9,0,"> Jun 30, 2019 1:29:32 PM com.orientechnologies.common.log.OLogManager log",Not
10,0,"INFO: Windows OS is detected, 262144 limit of open files will be set for the disk cache.",NL
11,0,"Jun 30, 2019 1:29:32 PM com.orientechnologies.common.log.OLogManager log",Not
12,0,INFO: 17118322688 B/16325 MB/15 GB of physical memory were detected on machine,NL
13,0,"Jun 30, 2019 1:29:32 PM com.orientechnologies.common.log.OLogManager log",Not
14,0,INFO: Detected memory limit for current process is 17118322688 B/16325 MB/15 GB,NL
15,0,"Jun 30, 2019 1:29:32 PM com.orientechnologies.common.log.OLogManager log",Not
16,0,INFO: JVM can use maximum 3628MB of heap memory,NL
17,0,"Jun 30, 2019 1:29:32 PM com.orientechnologies.common.log.OLogManager log",Not
18,0,INFO: Because OrientDB is running outside a container 12% of memory will be left unallocated according to the setting 'memory.leftToOS' not taking into account heap memory,NL
19,0,"Jun 30, 2019 1:29:32 PM com.orientechnologies.common.log.OLogManager log",Not
20,0,"INFO: OrientDB auto-config DISKCACHE=10,737MB (heap=3,628MB os=16,325MB)",Not
21,0,"Jun 30, 2019 1:29:32 PM com.orientechnologies.common.log.OLogManager log",Not
22,0,INFO: System is started under an effective user : `test`,NL
23,0,"Jun 30, 2019 1:29:32 PM com.orientechnologies.common.log.OLogManager log",Not
24,0,INFO: Allocation of 163202 pages.,NL
25,0,"Jun 30, 2019 1:29:33 PM com.orientechnologies.common.log.OLogManager log",Not
26,0,"INFO: WAL maximum segment size is set to 6,144 MB",NL
27,0,"Jun 30, 2019 1:29:33 PM com.orientechnologies.common.log.OLogManager log",Not
28,0,INFO: Page size for WAL located in Z:\PortableApps\eclipse-oxygen-2\workspace\orientdbtest\.\db\test is set to 4096 bytes.,NL
29,0,"Jun 30, 2019 1:29:33 PM com.orientechnologies.common.log.OLogManager log",Not
30,0,WARNING: Storage 'test' was not closed properly. Will try to recover from write ahead log,NL
31,0,"Jun 30, 2019 1:29:33 PM com.orientechnologies.common.log.OLogManager log",Not
32,0,INFO: Looking for last checkpoint...,NL
33,0,"Jun 30, 2019 1:29:33 PM com.orientechnologies.common.log.OLogManager log",Not
34,0,"INFO: Checkpoints are absent, the restore will start from the beginning.",NL
35,0,"Jun 30, 2019 1:29:33 PM com.orientechnologies.common.log.OLogManager log",Not
36,0,INFO: Data restore procedure is started.,NL
37,0,"Jun 30, 2019 1:29:34 PM com.orientechnologies.common.log.OLogManager log",Not
38,0,"WARNING: Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OEmptyWALRecord{lsn=OLogSequenceNumber{segment=1, position=18}} will be skipped during data restore",NL
39,0,"Jun 30, 2019 1:29:34 PM com.orientechnologies.common.log.OLogManager log",Not
40,0,"INFO: 1 operations were processed, current LSN is OLogSequenceNumber{segment=1, position=18} last LSN is OLogSequenceNumber{segment=2, position=18}",NL
41,0,"Jun 30, 2019 1:29:34 PM com.orientechnologies.common.log.OLogManager log",Not
42,0,WARNING: Non tx operation was used during data modification we will need index rebuild.,NL
43,0,"Jun 30, 2019 1:29:36 PM com.orientechnologies.common.log.OLogManager log",Not
44,0,"WARNING: Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OEmptyWALRecord{lsn=OLogSequenceNumber{segment=2, position=18}} will be skipped during data restore",NL
45,0,"Jun 30, 2019 1:29:39 PM com.orientechnologies.common.log.OLogManager log",Not
46,0,INFO: Storage data recover was completed,NL
47,0,"Jun 30, 2019 1:29:39 PM com.orientechnologies.common.log.OLogManager log",Not
48,0,"INFO: Storage 'plocal:Z:\PortableApps\eclipse-oxygen-2\workspace\orientdbtest\.\db/test' is opened under OrientDB distribution : 3.0.21 - Veloce (build 1d8b0c01ca8fe12a516bba355681e3ec8b218d1d, branch 3.0.x)",Not
49,0,"Jun 30, 2019 1:29:39 PM com.orientechnologies.common.log.OLogManager log",Not
50,0,INFO: $ANSI{green {db=test}} Wait till indexes restore after crash was finished.,NL
51,0,"Jun 30, 2019 1:29:39 PM com.orientechnologies.common.log.OLogManager log",Not
52,0,INFO: $ANSI{green {db=test}} Index 'ORole.name' is a durable automatic index and will be added as is without rebuilding,NL
53,0,"Jun 30, 2019 1:29:39 PM com.orientechnologies.common.log.OLogManager log",Not
54,0,INFO: $ANSI{green {db=test}} Index 'ORole.name' was added in DB index list,NL
55,0,"Jun 30, 2019 1:29:39 PM com.orientechnologies.common.log.OLogManager log",Not
56,0,INFO: $ANSI{green {db=test}} Index 'OUser.name' is a durable automatic index and will be added as is without rebuilding,NL
57,0,"Jun 30, 2019 1:29:39 PM com.orientechnologies.common.log.OLogManager log",Not
58,0,INFO: $ANSI{green {db=test}} Index 'OUser.name' was added in DB index list,NL
59,0,"Jun 30, 2019 1:29:39 PM com.orientechnologies.common.log.OLogManager log",Not
60,0,INFO: $ANSI{green {db=test}} Index 'dictionary' is a durable non-automatic index and will be added as is without rebuilding,NL
61,0,"Jun 30, 2019 1:29:39 PM com.orientechnologies.common.log.OLogManager log",Not
62,0,INFO: $ANSI{green {db=test}} Index 'dictionary' was added in DB index list,NL
63,0,"Jun 30, 2019 1:29:39 PM com.orientechnologies.common.log.OLogManager log",Not
64,0,INFO: $ANSI{green {db=test}} Index 'OFunction.name' is a durable automatic index and will be added as is without rebuilding,NL
65,0,"Jun 30, 2019 1:29:39 PM com.orientechnologies.common.log.OLogManager log",Not
66,0,INFO: $ANSI{green {db=test}} Index 'OFunction.name' was added in DB index list,NL
67,0,"Jun 30, 2019 1:29:39 PM com.orientechnologies.common.log.OLogManager log",Not
68,0,"INFO: $ANSI{green {db=test}} 4 indexes were restored successfully, 0 errors",NL
69,0,"Jun 30, 2019 1:29:39 PM com.orientechnologies.common.log.OLogManager log",Not
70,0,INFO: $ANSI{green {db=test}} Indexes restore after crash was finished.,NL
71,0,size: 675,Not
72,0,"Jun 30, 2019 1:29:39 PM com.orientechnologies.common.log.OLogManager log",Not
73,0,SEVERE: $ANSI{green {db=test}} Magic number verification failed for page `1425` of `pupil.pcl`.,NL
74,0,"Jun 30, 2019 1:29:39 PM com.orientechnologies.common.log.OLogManager log",Not
75,0,SEVERE: $ANSI{green {db=test}} Magic number verification failed for page `1425` of `pupil.pcl`.,NL
76,0,java.lang.Exception,Not
77,0,	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.dumpStackTrace(OWOWCache.java:2306),Not
78,0,	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.verifyMagicAndChecksum(OWOWCache.java:2264),Not
79,0,	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadFileContent(OWOWCache.java:2164),Not
80,0,	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.load(OWOWCache.java:1137),Not
81,0,	at com.orientechnologies.orient.core.storage.cache.chm.AsyncReadCache.lambda$doLoad$0(AsyncReadCache.java:150),Not
82,0,	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853),Not
83,0,	at com.orientechnologies.orient.core.storage.cache.chm.AsyncReadCache.doLoad(AsyncReadCache.java:147),Not
84,0,	at com.orientechnologies.orient.core.storage.cache.chm.AsyncReadCache.loadForRead(AsyncReadCache.java:115),Not
85,0,	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.loadPageForWrite(OAtomicOperation.java:111),Not
86,0,	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPageForWrite(ODurableComponent.java:129),Not
87,0,	at com.orientechnologies.orient.core.storage.cluster.v1.OPaginatedClusterV1.addEntry(OPaginatedClusterV1.java:1720),Not
88,0,	at com.orientechnologies.orient.core.storage.cluster.v1.OPaginatedClusterV1.createRecord(OPaginatedClusterV1.java:502),Not
89,0,	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCreateRecord(OAbstractPaginatedStorage.java:4547),Not
90,0,	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:5133),Not
91,0,	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2161),Not
92,0,	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1993),Not
93,0,	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2732),Not
94,0,	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.doCommit(OMicroTransaction.java:363),Not
95,0,	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.commit(OMicroTransaction.java:166),Not
96,0,	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.endMicroTransaction(ODatabaseDocumentEmbedded.java:799),Not
97,0,	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.executeSaveRecord(ODatabaseDocumentEmbedded.java:789),Not
98,0,	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveNew(OTransactionNoTx.java:244),Not
99,0,	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:174),Not
100,0,	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:2099),Not
101,0,	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:2064),Not
102,0,	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:85),Not
103,0,	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2169),Not
104,0,	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:2160),Not
105,0,	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:118),Not
106,0,	at test.Test.main(Test.java:34),Not
110,1,## Steps to reproduce,NL
112,0,> 	public static void main(String[] args),Not
113,0,	{,Not
114,0,"		try (OrientDB odb = new OrientDB(""""embedded:./db"""", OrientDBConfig.defaultConfig()))",Not
115,0,		{,Not
116,0,"		    odb.createIfNotExists(""""test"""", ODatabaseType.PLOCAL); 	",Not
117,0,"		    ODatabaseSession db = odb.open(""""test"""", """"admin"""", """"admin"""");",Not
118,0,"		    db.getMetadata().getSchema().getOrCreateClass(""""pupil"""");",Not
119,0,"		    long size = db.countClass(""""pupil"""");",Not
120,0,"		    System.out.println(""""size: """"+size);",Not
121,0,		    long t = System.currentTimeMillis();,Not
122,0,		    db.declareIntent(new OIntentMassiveInsert());,Not
123,0,		    for (int i=0; i<1000000; i++),Not
124,0,		    {,Not
125,0,"			    OElement doc = db.newElement(""""pupil"""");",Not
126,0,"			    doc.setProperty(""""id"""",size+i);",Not
127,0,"			    doc.setProperty(""""json"""", randomString());",Not
128,0,			    doc.save();,Not
129,0,			    if (i % 100 == 0),Not
130,0,			    {,Not
131,0,			    	System.out.println(System.currentTimeMillis()-t);,Not
132,0,			    	t = System.currentTimeMillis();,Not
133,0,			    	db.commit();,Not
134,0,			    },NL
135,0,		    },Not
136,0,		},Not
138,0,	},Not
141,1,force stop the JVM while the program is running.,NL
142,1,then restart,NL
0,1,"The list, currently, is created via the CategoryDaoImpl.readActiveSubCategoriesByCategory(..) method. This method queries the database via the defaultParentCategory, which possibly misses additional categories that are associated via CategoryXrefImpl, but not via the defaultParentCategory. This is rare, but possible. Also, since ordering is described in CategoryXrefImpl, this query does not take advantage of the proper ordering of subcategories.",NL
2,1,An enhancement/fix would be to alter the query to use the category xref table instead.,NL
0,1,as found by @virendrachaudhary06 in this comment: https://github.com/intuit/karate/issues/206#issuecomment-340235669,NL
0,1,version:redisson-2.2.9,Not
1,1,exception:,NL
2,0,Caused by: java.lang.NullPointerException,Not
3,0,at com.simontuffs.onejar.OneJarFile.getInputStream(OneJarFile.java:116),Not
4,0,at com.simontuffs.onejar.OneJarURLConnection.getInputStream(OneJarURLConnection.java:51),Not
5,0,at java.net.URL.openStream(URL.java:1037),Not
6,0,at org.redisson.Version.logVersion(Version.java:35),Not
7,0,at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:139),Not
8,0,at org.redisson.cluster.ClusterConnectionManager.<init>(ClusterConnectionManager.java:65),Not
9,0,at org.redisson.Redisson.<init>(Redisson.java:100),Not
10,0,at org.redisson.RedissonExt.create(RedissonExt.java:82),Not
11,0,... 60 more,NL
13,1,**org.redisson.Version.java**,Not
14,1,should catch Exception instead of IOException,NL
0,1,`MongoRepositoriesAutoConfiguration` should be after `MongoDataAutoConfiguration` not `MongoAutoConfiguration` otherwise it goes and creates a bunch of beans that `MongoDataAutoConfiguration` want to create itself (like the `MongoMapperContext`).,NL
0,1,This should be similar to memcmp() or strcmp() as described in the java-doc.,NL
2,1,"This is because the [ByteBufUtil.compare(ByteBuf, ByteBuf)](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/ByteBufUtil.java#L226) compare the `ByteBuf`s as integers and not raw bytes.",NL
4,0,```,Not
5,1,Sample Code,NL
6,0,========,Not
7,0,public static void main(String[] args) {,Not
8,0,"    ByteBuf buf1 = Unpooled.wrappedBuffer(""""1234"""".getBytes()).order(ByteOrder.LITTLE_ENDIAN);",Not
9,0,"    ByteBuf buf2 = Unpooled.wrappedBuffer(""""4321"""".getBytes()).order(ByteOrder.LITTLE_ENDIAN);",Not
10,0,"    System.out.println(""""\""""1234\"""".compareTo(\""""4321\"""") = """" + buf1.compareTo(buf2));",Not
12,0,"    buf1 = Unpooled.wrappedBuffer(""""1234"""".getBytes()).order(ByteOrder.BIG_ENDIAN);",Not
13,0,"    buf2 = Unpooled.wrappedBuffer(""""4321"""".getBytes()).order(ByteOrder.BIG_ENDIAN);",Not
14,0,"    System.out.println(""""\""""1234\"""".compareTo(\""""4321\"""") = """" + buf1.compareTo(buf2));",Not
15,0,},Not
17,1,Output,NL
18,0,=====,Not
19,0,"""""1234"""".compareTo(""""4321"""") = 1",Not
20,0,"""""1234"""".compareTo(""""4321"""") = -1",Not
21,0,```,Not
0,1,"My app has no field named """"loadFactor"""" - I assume it's some internal MapDB error?",NL
2,0,.RuntimeException: Could not set field value: loadFactor - class java.util.LinkedHashMap,NL
5,1,It isn't happening on all uses of my Map - not sure what the factor is at this point.  Looking for suggestions on how to track it down.,NL
0,1,The retry logic to try and start a river should also handle index missing case if it has not propagated yet.,NL
0,1,"I'm using Netty WebSockets with HTTPS. When performing the handshake, the header field `sec-websocket-origin` is set to a value starting with `http://`, which looks weird.",NL
1,1,There is nothing about `sec-websocket-origin` in the RFC.,NL
2,1,"The string `http` is set inconditionnally in `io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13`, line 165.",NL
3,1,I'm using Netty-4.1.0.CR7.,NL
0,1,See https://github.com/spring-projects/spring-boot/issues/9128#issuecomment-358980565 (second paragraph) for the original discussion.,NL
2,1,"In short: the runtime classpath should have application classes from `BOOT-INF/classes` before libraries taken from `BOOT-INF/lib`. This would match the observed behaviour of Eclipse, Maven, Surefire, etc.",NL
4,1,The current implementation of the `Repackager` respects that order but without any guarantee: it is more because of the current implementation rather than by specification. There is also no test case to assert this order is respected.,NL
0,1,"While using the method `OrientBaseGraph.addEdge(Object, Vertex, Vertex, String)` I found some issues trying to define the class name parameter. Looking into the method's implementation it is possible to see that the first part of the method parses the `id` parameter considering the following notation: `class:ClassName,cluster:ClusterName`. Although, as soon as the first part finishes a new parser is executed which generates an invalid class name. The following JUnit test illustrates the problem:",NL
2,0,``` java,Not
3,0,import org.junit.After;,Not
4,0,import org.junit.Before;,Not
5,0,import org.junit.Test;,Not
7,0,import com.tinkerpop.blueprints.impls.orient.OrientEdgeType;,Not
8,0,import com.tinkerpop.blueprints.impls.orient.OrientGraph;,Not
9,0,import com.tinkerpop.blueprints.impls.orient.OrientGraphFactory;,Not
10,0,import com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx;,Not
11,0,import com.tinkerpop.blueprints.impls.orient.OrientVertex;,Not
12,0,import com.tinkerpop.blueprints.impls.orient.OrientVertexType;,Not
14,0,public class OrientGraphTest {,Not
16,0,private OrientGraphNoTx graphDbNoTx;,Not
17,0,private OrientGraph graphDbTx;,Not
19,0,@Before,NL
20,0,public void setupDb() {,Not
21,0,"        OrientGraphFactory orientGraphFactory = new OrientGraphFactory(""""memory:testdb"""");",Not
22,0,this.graphDbNoTx = orientGraphFactory.getNoTx();,Not
23,0,this.graphDbTx = orientGraphFactory.getTx();,Not
24,0,},Not
26,0,@After,NL
27,0,public void closeDatabase() {,Not
28,0,this.graphDbTx.drop();,Not
29,0,},Not
31,0,@Test,NL
32,0,public void shouldAddVertexAndEdgeInTheSameCluster() {,Not
33,0,"        OrientVertexType deviceVertex = this.graphDbNoTx.createVertexType(""""Device"""");",Not
34,0,"        OrientEdgeType edgeType = this.graphDbNoTx.createEdgeType(""""Link"""");",Not
36,0,"        edgeType.addCluster(""""Links"""");",Not
38,0,"        OrientVertex dev1 = this.graphDbTx.addVertex(""""Device"""");",Not
39,0,"        OrientVertex dev2 = this.graphDbTx.addVertex(""""Device"""");",Not
41,0,"        this.graphDbTx.addEdge(""""class:Link,cluster:Links"""", dev1, dev2, null);",Not
42,0,},Not
44,0,},Not
45,0,```,Not
47,1,In the end the following exception is thrown:,NL
49,0,``` java,Not
50,0,java.lang.IllegalArgumentException: Invalid field name 'out_Link%2Ccluster%3ALinks'. Character '%' is invalid,NL
51,0,at com.orientechnologies.orient.core.record.impl.ODocument.checkFieldName(ODocument.java:1668),Not
52,0,at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:761),Not
53,0,at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:673),Not
54,0,at com.tinkerpop.blueprints.impls.orient.OrientVertex.createLink(OrientVertex.java:150),Not
55,0,at com.tinkerpop.blueprints.impls.orient.OrientVertex.addEdge(OrientVertex.java:708),Not
56,0,at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.addEdge(OrientBaseGraph.java:527),Not
57,0,at br.ind.datacom.provisioning.orientdb.cluster.OrientGraphTest.shouldAddVertexAndEdgeInTheSameCluster(OrientGraphTest.java:41),Not
58,0,...,Not
59,0,```,Not
0,1,In Netty.4.0.24.final.,NL
2,1,"In class io.netty.util.Recycler, there's a DEFAULT_MAX_CAPACITY variable to constrain the size of the stack in Recycler. From INITIAL_CAPACITY, whenever the stack is full, it's size doubled until hitting the DEFAULT_MAX_CAPACITY limit(Line 341 in Netty.4.0.24.final). ",NL
3,0,![image](https://cloud.githubusercontent.com/assets/1115061/5156597/45b7fa9a-730a-11e4-89aa-bb1f87c47428.png),Not
4,1,"As you can see in the image above, stack size is constrained by maxCapacity. And if the size > maxCapacity, this check will fail forever, beacuse the check use """"if (size == maxCapacity)"""" rather than """"if (size > maxCapacity)"""".  And there's a way to set size bigger than maxCapacity.",NL
6,1,"In class WeakOrderQueue which is an inner class in Recycler, there's a method called """"transfer"""" which can also double the stack size in Recycler, but there's no check to ensure the stack size not exceed DEFAULT_MAX_CAPACITY limit(Line 218 in Netty.4.0.24.final) like the one mentioned before. ",NL
7,0,![image](https://cloud.githubusercontent.com/assets/1115061/5156598/5a17c01a-730a-11e4-873b-1e65ee539db3.png),Not
8,1,"In the image above, variable """"to"""" is a stack in Recycler and count is resources's quantity recycled by other thread rather than the Recycler's owner. If there's no enough space for those resources to be recycled, the stack's size will be doubled. I think there should have a check for the stack size here. And whenever the stack size greater than maxCapacity, it can grow infinitely.",NL
0,1,"The NPE was triggered when calling the constructor of `ExtractParameterRefactoring`, when the workspace is just opened and no file has been successfully parsed and typechecked by the parse controller.",NL
0,1,"When upgrading from 1.x to 2.0, a field that has only a `search_analyzer` specified will throw an exception and prevent the node from starting.  Really, the field does have an `index_analyzer`, set to `default`.  We should be able to migrate this mapping to a 2.0 compatible version.",NL
2,1,Relates to #14313,NL
0,1,"The incorrect result can be seen in the Interactive Calculator example (actions/tools/Expr.g4) in chapter 10 of the ANTLR4 book, page 181, in which parenthesized expressions always yield 0. ",NL
2,1,"When a rule invokes itself recursively, and no label is used, incorrect code is generated when an action references either a variable returned by the recursive call, or any of the subexpression's predefined attributes `text`, `start`, `stop`, or `ctx`. The generated code refers to the current rule's context;  instead it should refer to the child's context. In the calculator example, `$e.v` incorrectly accesses `_localctx.v` (the field where the current rule should put its result, which is initially 0 if numeric or null if a reference type). Thus, the example action assigns the uninitialized field to itself. Instead it should access `_localctx.e.v` (the result from the recursive invocation).",NL
4,1,"The problem does not occur when the grammar assigns a label renaming the self-invocation - for example, it would be ok if changed to `'(' ee=e ')' {$v = $ee.v;} ;`    ",NL
0,1,Test `testInstallNpmsThenUninstallOneDependency` in class `InstallUninstallNPMPluginUITest` fails randomly with the following exception:,NL
2,0,```,Not
3,0,IResourceDescription in index must not be an instance of ResourceDescriptionWithoutModuleUserData but it was. URI: file:/var/lib/build/workspace/n4js-extended-nightly/n4js-n4/tests/com.enfore.n4js.ui.tests/target/work/data/.metadata/.plugins/org.eclipse.n4js.external.libraries/.n4npm/node_modules/lodash/fp/matches.js,NL
4,0,IResourceDescription in index must not be an instance of ResourceDescriptionWithoutModuleUserData but it was. URI: file:/var/lib/build/workspace/n4js-extended-nightly/n4js-n4/tests/com.enfore.n4js.ui.tests/target/work/data/.metadata/.plugins/org.eclipse.n4js.external.libraries/.n4npm/node_modules/lodash/bind.js,NL
5,0,[...],Not
6,0,	at org.junit.Assert.fail(Assert.java:88),Not
7,0,	at org.junit.Assert.assertTrue(Assert.java:41),Not
8,0,	at org.eclipse.n4js.tests.builder.AbstractBuilderTest.assertXtextIndexIsValid(AbstractBuilderTest.java:274),Not
9,0,	at org.eclipse.n4js.tests.builder.AbstractBuilderTest.waitForAutoBuild(AbstractBuilderTest.java:204),Not
10,0,	at org.eclipse.n4js.tests.builder.AbstractBuilderTest.waitForAutoBuild(AbstractBuilderTest.java:197),Not
11,0,	at com.enfore.n4js.tests.externalPackages.InstallUninstallNPMPluginUITest.testInstallNpmsThenUninstallOneDependency(InstallUninstallNPMPluginUITest.java:184),Not
12,0,```,Not
14,1,For sample builds showing this failure see internal Jenkins build server.,NL
0,1,I'm using Spring OAuth 2.0.10.,NL
2,1,I have an OAuth Application Client.,NL
3,1,"When my access token (AT) expires, Spring OAuth uses the refresh token (RT) to get a new AT from the Authorization Server (AS).",NL
4,1,"Problem is if the AS returns a new RT along the new AT, Spring OAuth doesn't pick the new RT and continues using the old RT.",NL
5,1,"So on next refresh, I'll get an error.",NL
7,1,This is due to https://github.com/spring-projects/spring-security-oauth/blob/b055772adbb9c10497b1077a0480bf2c2649fb04/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/client/token/AccessTokenProviderChain.java#L166.,NL
9,1,It should check if there's a RT in the AS response.,NL
10,1,"If no, just keep using the old RT. If yes, use the new RT.",NL
12,1,"In my scenario, here's the request to the token endpoint :  ",NL
14,0,```,Not
15,0,POST /oidc/oauth2/token HTTP/1.1,Not
16,0,grant_type=refresh_token&refresh_token=90a6e10e2801925583b69ba076c195,Not
17,0,```,Not
19,1,And the response :,NL
21,0,```,Not
22,0,{,Not
23,0,"   """"access_token"""":""""b6f54d7326354cdfb12227c96b6894a"""",",Not
24,0,"   """"token_type"""":""""Bearer"""",",Not
25,0,"   """"expires_in"""":3600,",Not
26,0,"   """"scope"""":""""openid hello.say"""",",NL
27,0,"   """"refresh_token"""":""""e2f9d5d05ed793d2b096a59dcde10e2"""",",Not
28,0,"   """"id_token"""":""""eyJhbGciOiJSUzI1NiJ9.eyJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhbGljZSIsInN1YiI6IkNHUjBXTEpaNFdEb1p6ZXExM3h3UXciLCJpYXQiOjE0NzAyOTUxNDgsImV4cCI6MTQ3MDI5ODc0NywiaXNzIjoiYWNjb3VudHMudGFsZW5kLmNvbSIsImdpdmVuX25hbWUiOiJhbGljZSIsImZhbWlseV9uYW1lIjoiYWxpY2UiLCJlbWFpbCI6ImFsaWNlQGdtYWlsLmNvbSIsIm5hbWUiOiJhbGljZSBhbGljZSIsImF1ZCI6IkRCUW91c1N5OFpLNEFBIiwiYXpwIjoiREJRb3VzU3k4Wks0QUEiLCJhdF9oYXNoIjoiU2pyZkF4N2ozM2VvRWF4Vi1JeXRIQSJ9.XxTitaQ5RO7MKfphbKjb0cErBHLDTimj1UTYkYRN1M_EhDnS6TvSHGoryCwMhQ_yANdWOeqZeX_IUmQu2Wj549d_HpLAqzlzrzc1SAbd0nucjWoH3tcCZ2WsuOLigZvhJZpvyj-v-Z2Ov8usk_-fXAP0e-p-MpvGinQ3op-BJQARq2ktM07hQTs8tcVaekpMrjplu-MlxNmqeKSMOQI2TERFZnQRfIYFTQvbCm7hxIs1YJoHnFAh2R_TA_14AJYMBRKXI1yi_EvdJvBkfh-3b7Dxr4pIRIty6aRcsys_9jqF0y4Wdw9Dq6R3GgWgSgvOuyDxq5rmVaR7jLkSw2HVDw""""",Not
29,0,},Not
30,0,```,Not
32,1,Spring OAuth keeps using the old RT (90a6e10e2801925583b69ba076c195) and not the new one (e2f9d5d05ed793d2b096a59dcde10e2).,NL
34,1,Extract from OAuth2 specs :,NL
35,1,See https://tools.ietf.org/html/rfc6749#section-6,NL
37,1,"> The authorization server MAY issue a new refresh token, in which case the client MUST discard the old refresh token and replace it with the new refresh token.  The authorization server MAY revoke the old refresh token after issuing a new refresh token to the client.  If a new refresh token is issued, the refresh token scope MUST be identical to that of the refresh token included by the client in the request.",NL
0,1,"lberki has pushed a fix for [issue 1300](https://github.com/bazelbuild/bazel/issues/1300) in order to fix building on windows related to cr lf woes, but now I am getting a different error:",NL
2,0,$ ./compile.sh,Not
4,0,```,Not
5,0,INFO: You can skip this first step by providing a path to the bazel binary as second argument:,NL
6,0,INFO:    ./compile.sh compile /path/to/bazel,Not
7,0,🍃  Building Bazel from scratch......,NL
8,0,🍃  Building Bazel with Bazel.,NL
9,0,.WARNING: C:/temp/bazel.Klhij5XN/out/external/bazel_tools/WORKSPACE:1: Workspace name in C:/temp/bazel.Klhij5XN/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.,NL
10,0,ERROR: C:/bazel/tools/build_rules/genproto.bzl:28:75: syntax error at '\': expected expression.,NL
11,0,ERROR: C:/bazel/tools/build_rules/genproto.bzl:28:9: missing else clause in conditional expression or semicolon before if.,NL
12,0,ERROR: C:/bazel/src/BUILD:127:1: error loading package 'src/main/protobuf': Extension 'tools/build_rules/genproto.bzl' has errors and referenced by '//src:embedded_tools'.,Not
13,0,ERROR: Loading failed; build aborted.,NL
14,0,INFO: Elapsed time: 0.931s,Not
15,0,```,Not
17,1,the commit id is 307dc0f627ca8f535a72beea7ed62196ee5553af,NL
0,1,We have a 100 of them in ci.bazel.io.,NL
0,1,Beans of two different types are required:,NL
2,1,- `org.elasticsearch.client.Client`,Not
3,1,- `org.springframework.data.elasticsearch.core.convert.ElasticsearchConverter`,Not
5,1,"If either of these is missing, the auto-configuration will fail rather than backing off. ",NL
0,1,At the moment Tenant management API specification defines that payload (without any mandatory parameters) is required during tenant creation. The implementation at the moment accepts empty body and adds 'enabled' field in that case. Empty body is also used in getting started examples.,NL
2,1,We need to align specification with the implementation and examples.,NL
0,0,"http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=windows-x86_64/936/consoleFull",Not
3,0,There was 1 failure:,NL
4,0,1) testGetTargetPathAbsolute(com.google.devtools.build.lib.rules.repository.RepositoryFunctionTest),Not
5,0,java.lang.AssertionError: expected:<A:/b/c> but was:</b/c>,Not
6,0,at org.junit.Assert.fail(Assert.java:88),Not
7,0,at org.junit.Assert.failNotEquals(Assert.java:743),Not
8,0,at org.junit.Assert.assertEquals(Assert.java:118),Not
9,0,at org.junit.Assert.assertEquals(Assert.java:144),Not
12,1,"According to some of the error message, my guess the culprit is ca99bb71b8120e61a3bbde8e54f1a9488fa0478f ",NL
13,0,//cc @laszlocsomor,NL
0,1,### Issue description,Not
1,1,When trying to download movie with Dash Downloader it fails with error:,NL
2,1,"""""Unbounded index for representation: ...""""",NL
4,1,"Seems, that issue caused by these part of code in DashDownloader.java class in getSegments method:",NL
5,0,```,Not
6,0,int segmentCount = index.getSegmentCount(C.TIME_UNSET);,Not
7,0,if (segmentCount == DashSegmentIndex.INDEX_UNBOUNDED) {,Not
8,0,"    throw new DownloadException(""""Unbounded index for representation: """" + key);",NL
9,0,},Not
10,0,```,Not
12,1,"If `C.TIME_UNSET` is always used as parameter, then BaseSegment code rely on `<SegmentTimeline>` tag in mpd file to get segments count. But there is no `<SegmentTimeline>` tag in specific mpd.",NL
14,1,"As a workaround I replaced above code with next lines, and download started successfully:",NL
15,0,```,Not
16,0,long periodDurationUs = manifest.getPeriodDurationUs(key.periodIndex);,Not
17,0,int segmentCount = index.getSegmentCount(periodDurationUs);,Not
18,0,if (segmentCount == DashSegmentIndex.INDEX_UNBOUNDED) {,Not
19,0,"    throw new DownloadException(""""Unbounded index for representation: """" + key);",NL
20,0,},Not
21,0,```,Not
23,1,But I'm not sure that it is a legit way to fix it and which problems my fix may bring.,NL
25,1,### Reproduction steps,Not
26,1,Try to download video with the next code:,NL
27,0,```,Not
28,0,"File downloadFolder = new File(""""/storage/emulated/0/downloaded_movies/"""");",Not
29,0,"SimpleCache cache = new SimpleCache(downloadFolder, new NoOpCacheEvictor());",Not
31,0,DefaultHttpDataSourceFactory factory = new DefaultHttpDataSourceFactory(userAgent);,Not
32,0,"DownloaderConstructorHelper helper = new DownloaderConstructorHelper(cache, factory);",Not
33,0,"DashDownloader dashDownloader = new DashDownloader(mpdUri, helper);",Not
34,0,dashDownloader.download(new Downloader.ProgressListener() {,Not
35,0,@Override,NL
36,0,"    public void onDownloadProgress(Downloader downloader, float downloadPercentage, long downloadedBytes) {",Not
37,0,...,Not
38,0,},Not
39,0,});,Not
40,0,```,Not
42,1,### Link to test content,NL
43,0,https://media.axprod.net/TestVectors/v7-Clear/Manifest_1080p.mpd,Not
45,1,### Version of ExoPlayer being used,NL
46,1,2.6.1,Not
48,1,### Device(s) and version(s) of Android being used,NL
49,1,Not a device specific. I used Nexus 9 Android 7.1.1,NL
51,1,### A full bug report captured from the device,NL
52,1,Bug report sent by email.,NL
0,1,"With #4730 the `Server` header is meant to be disabled by default, but this only works when SSL is not used. Given that disabling the server header is primarily for security reasons, having it work with SSL is pretty essential.",NL
2,1,This is because the HTTPS and HTTP connector factories in `JettyEmbeddedServletContainerFactory` don't configure the `HttpConfiguration` in the same way.,NL
4,1,Tested with Spring Boot `1.4.2.RELEASE` with the default Jetty version (9.3.14),NL
0,0,class：org.redisson.spring.data.connection.RedissonConnection.java,Not
1,1,code line：882,Not
2,1,code segment：,NL
3,0,"<T> T write(byte[] key, Codec codec, RedisCommand<?> command, Object... params) {",Not
4,0,"	RFuture<T> f = executorService.writeAsync(key, codec, command, params);",Not
5,0,	indexCommand(command);,Not
6,0,	return sync(f);,Not
7,0,},Not
9,1,bug：return null when not used in pipeline / transaction.,NL
11,1,### Expected behavior,Not
12,1,not return null when not used in pipeline / transaction.,NL
13,1,### Actual behavior,Not
14,1,return null when not used in pipeline / transaction.,NL
15,1,### Steps to reproduce or test case,NL
16,0,"public Boolean setNx(String key, String value, long expireMillis) {",Not
17,0,	return stringRedisTemplate.execute(new RedisCallback<Boolean>() {,Not
18,0,		@Override,NL
19,0,		public Boolean doInRedis(RedisConnection connection) throws DataAccessException {,Not
20,0,"			return connection.set(key.getBytes(), value.getBytes(), Expiration.milliseconds(expireMillis),",NL
21,0,					SetOption.SET_IF_ABSENT);,Not
22,0,		},Not
23,0,"	}, true);",Not
24,0,},Not
25,1,### Redis version,Not
26,1,Redis-x64-3.0.500,Not
27,1,### Redisson version,Not
28,1,3.11.1,Not
29,1,### Redisson configuration,Not
0,1,Trying to set a negative `default` or `lowerBound` value in an elkm file raises an error.,NL
2,1,The used grammar rule is `('default' '=' defaultValue=XExpression)?`.,NL
0,1,"Hi,",NL
2,1,recently the following tests started to fail sporadically:,NL
4,1,- `LogFileWebEndpointAutoConfigurationTests.logFileWebEndpointIsAutoConfiguredWhenExternalFileIsSet `,Not
5,1,- `DiskSpaceHealthContributorAutoConfigurationTests.runWhenPathDoesNotExistShouldCreateIndicator `,Not
7,1,Both seem to be throwing similar errors like this:,NL
9,0,```,Not
10,0,Caused by: org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.io.File] for value 'external.log'; nested exception is java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [external.log]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.,NL
11,0,	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47),Not
12,0,	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:191),Not
13,0,	at org.springframework.boot.context.properties.bind.BindConverter$CompositeConversionService.convert(BindConverter.java:170),Not
14,0,	at org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:96),Not
15,0,	at org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:88),Not
16,0,	at org.springframework.boot.context.properties.bind.Binder.bindProperty(Binder.java:434),Not
17,0,	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:379),Not
18,0,	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:319),Not
19,0,	... 142 more,NL
20,0,Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [external.log]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.,NL
21,0,	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1385),Not
22,0,	at org.apache.catalina.loader.WebappClassLoaderBase.getResource(WebappClassLoaderBase.java:1038),Not
23,0,	at org.springframework.core.io.ClassPathResource.resolveURL(ClassPathResource.java:155),Not
24,0,	at org.springframework.core.io.ClassPathResource.exists(ClassPathResource.java:142),Not
25,0,	at org.springframework.boot.convert.StringToFileConverter.convert(StringToFileConverter.java:48),Not
26,0,	at org.springframework.boot.convert.StringToFileConverter.convert(StringToFileConverter.java:34),Not
27,0,	at org.springframework.core.convert.support.GenericConversionService$ConverterAdapter.convert(GenericConversionService.java:385),Not
28,0,	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41),Not
29,0,```,Not
31,1,"I tried fixing it directly, but I can't see what's going wrong in these cases.",NL
33,1,"Cheers,",NL
34,1,Christoph,NL
0,1,Backport of gh-25110,NL
0,1,In the estimation request there should there is an incorrect assumption that there is a fulfillmentoption associated with the fulfillment group.,NL
0,1,"In order to finally lay `--incompatible_do_not_split_linking_cmdline` to rest, we need to make some changes to `unix_cc_configure.bzl` which are not backward compatible. Therefore, we need to hide that behind a flag somehow.",NL
2,1,"One approach to do so is to expose Starlark incompatible flags to repository functions. However, when such a flag is changed, Starlark repositories are not invalidated and not rebuilt. (note that incorrectness of this pattern already exists at HEAD, because Starlark repository functions, well, depend on Starlark semantics)",NL
4,1,This blocks at least:,NL
6,0,https://github.com/bazelbuild/bazel/issues/10327,Not
7,0,https://github.com/bazelbuild/bazel/issues/9254,Not
0,1,"Creating a new project will create a folder that’s literally called `defaultSourceFolder`. That’s a bit silly, it should just be `source`.",NL
2,1,"Possibly introduced in c99726aad5a161d205d4988648041501a1f24781. That commit seems to indicate that a resource folder would similarly be called `defaultResourceFolder`, but I haven’t tested that.",NL
0,1,"I have accidently created an index with name """"."""" (dot). It was created without any problems. Tried to delete it and elastic did deleted whole my data on whole cluster.",NL
0,1,before 4.0.0.CR3 I do this with this code:,NL
2,0,```,Not
3,0,void broadcast(byte[] data) {,Not
4,0,ByteBuf msg = Unpooled.wrappedBuffer(data);,Not
5,0,for (Channel ch : channels) {,Not
6,0,ch.write(msg);,Not
7,0,},Not
8,0,},Not
9,0,```,Not
11,1,with CR3:,NL
13,0,```,Not
14,0,void broadcast(byte[] data) {,Not
15,0,ByteBuf msg = Unpooled.wrappedBuffer(data);,Not
16,0,for (Channel ch : channels) {,Not
17,0,msg.retain();,Not
18,0,ch.write(msg);,Not
19,0,},Not
20,0,},Not
21,0,```,Not
23,1,"after upgrade to CR5, the code not work again, seems like netty consume/copy(?) the ByteBuf in a asynchronization way now. And I change my code to:",NL
25,0,```,Not
26,0,void broadcast(byte[] data) {,Not
27,0,ByteBuf msg = Unpooled.wrappedBuffer(data);,Not
28,0,for (Channel ch : channels) {,Not
29,0,msg.retain();,Not
30,0,ch.write(msg.slice());,Not
31,0,},Not
32,0,},Not
33,0,```,Not
35,1,"I don't know this is the best way to do. I looked the netty-example project, the examples are all Request-Response. It would be great to add example to demonstrate the offical way to do Request->Broadcast.(e.g. chatting room)",NL
0,1,"An extension that is applied to the test class as well to a test method therein gets called twice. As far as I can tell, this behavior was different in the alpha version.",NL
2,1,"In my scenario this had undesired consequences and came as a surprise (I expected it to be called once), so I was initially sure it was a bug. After thinking about it for a while I'm not so sure any more. Maybe there is a use case for this?",NL
4,1,"More abstract this begs the question of the extension semantics. Does it mean """"call this extension at the implemented extension points"""" (then repeated calls make sense) or does it mean """"activate this extension for the implemented extension points"""" (in which case it should be idempotent).",NL
5,1,## Example,NL
7,0,``` java,Not
8,0,public class DoubleCallback implements BeforeTestExecutionCallback {,Not
10,0,@Override,NL
11,0,public void beforeTestExecution(TestExtensionContext context) throws Exception {,Not
12,0,"        System.out.println(""""Before """" + context.getDisplayName());",Not
13,0,},Not
15,0,},Not
17,0,@ExtendWith(DoubleCallback.class),Not
18,0,class DoubleCallbackTest {,Not
20,0,@Test,NL
21,0,@ExtendWith(DoubleCallback.class),Not
22,0,void test() { },Not
24,0,},Not
25,0,```,Not
27,1,Output:,NL
29,0,```,Not
30,0,Before test(),NL
31,0,Before test(),NL
32,0,```,Not
33,1,## Deliverables,Not
34,1,- [x] Add tests for the previous behavior.,NL
35,1,- [x] Fix the regression.,NL
36,1,- [x] Document semantics regarding parent and child extension contexts in the User Guide.,NL
0,1,Sample code :,NL
2,0,```,Not
3,0,OPartitionedDatabasePoolFactory poolFactory = new OPartitionedDatabasePoolFactory();,Not
4,0,"    OPartitionedDatabasePool pool = poolFactory.get(""""plocal:testdb"""", """"administrator"""", """"administrator"""");",Not
5,0,ODatabaseDocumentTx db = pool.acquire();,Not
6,0,db.close();,Not
7,0,pool.close();,Not
8,0,```,Not
10,1,"After closing the pool, in the later stage of application; getting the pool from the same factory and trying to acquire a new connection reports """"Pool is closed""""",NL
12,0,```,Not
13,0,java.lang.IllegalStateException: Pool is closed,NL
14,0,at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.checkForClose(OPartitionedDatabasePool.java:373),Not
15,0,at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:238),Not
16,0,```,Not
18,1,"The OPartitionedDatabasePoolFactory retains the pool instance and returns the same, which was closed, as PoolIdentity is same.",NL
0,1,### Expected behavior,Not
1,1,"`Mono.error(new IllegalStateException(""""boom"""")).log(""""foo"""", FINE)` logs at DEBUG level with SLF4J.",NL
3,1,### Actual behavior,Not
4,1,It always logs at ERROR level.,NL
6,1,### Steps to reproduce,NL
7,0,```java,Not
8,0,"Mono.error(new IllegalStateException(""""boom""""))",Not
9,0,"		    .log(""""foo"""", Level.FINEST)",Not
10,0,"		    .subscribe(v -> {}, e -> {});",Not
11,0,```,Not
12,0,>,Not
13,0,```,Not
14,0,20:29:11.251 [main] ERROR foo - onError(java.lang.IllegalStateException: boom),Not
15,0,20:29:11.258 [main] ERROR foo -,Not
17,0,```,Not
19,1,### Reactor Core version,Not
20,1,3.1.2,Not
0,1,"It looks like the """"Icon"""" from the MetaType model is not working when the component is a factory component. It only shows a """"broken image"""" image.",NL
0,1,This problem appears to have been introduced at some point in 1.4.0. It happens with 1.4.0.M1 which uses Tomcat 8.0.32. It does not happen with 1.3.3.RELEASE which also uses Tomcat 8.0.32.,NL
2,1,"When an application fails to start, the following two warnings are logged:",NL
4,0,```,Not
5,0,2016-03-08 10:02:07.076  WARN 42263 --- [ost-startStop-1] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [main] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:,NL
6,0,sun.misc.Unsafe.park(Native Method),Not
7,0,java.util.concurrent.locks.LockSupport.park(LockSupport.java:175),Not
8,0,java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429),Not
9,0,java.util.concurrent.FutureTask.get(FutureTask.java:191),Not
10,0,org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:972),Not
11,0,org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:224),Not
12,0,org.apache.catalina.core.StandardService.stopInternal(StandardService.java:502),Not
13,0,org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:224),Not
14,0,org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:790),Not
15,0,org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:224),Not
16,0,org.apache.catalina.startup.Tomcat.stop(Tomcat.java:355),Not
17,0,org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.stopSilently(TomcatEmbeddedServletContainer.java:194),Not
18,0,org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:175),Not
19,0,org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293),Not
20,0,org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141),Not
21,0,org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541),Not
22,0,org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118),Not
23,0,org.springframework.boot.SpringApplication.refresh(SpringApplication.java:768),Not
24,0,org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:362),Not
25,0,org.springframework.boot.SpringApplication.run(SpringApplication.java:308),Not
26,0,org.springframework.boot.SpringApplication.run(SpringApplication.java:1183),Not
27,0,org.springframework.boot.SpringApplication.run(SpringApplication.java:1172),Not
28,0,sample.web.staticcontent.SampleWebStaticApplication.main(SampleWebStaticApplication.java:33),Not
29,0,sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method),Not
30,0,sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62),Not
31,0,sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),Not
32,0,java.lang.reflect.Method.invoke(Method.java:498),Not
33,0,org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54),Not
34,0,org.springframework.boot.loader.Launcher.launch(Launcher.java:101),Not
35,0,org.springframework.boot.loader.Launcher.launch(Launcher.java:58),Not
36,0,org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59),Not
37,0,2016-03-08 10:02:07.076  WARN 42263 --- [ost-startStop-1] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [container-0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:,NL
38,0,java.lang.Thread.sleep(Native Method),Not
39,0,org.apache.catalina.core.StandardServer.await(StandardServer.java:407),Not
40,0,org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer$1.run(TomcatEmbeddedServletContainer.java:154),Not
41,0,```,Not
0,1,We’ve implemented it as `String.toRequestBody()` but I think we might be mistaken here. `to` feels like a conversion; `as` feels like a cast. I’d like to confirm what the precedents are and follow them.,NL
0,1,Child of https://github.com/checkstyle/checkstyle/issues/5777,NL
2,1,This issue specifically focuses on AvoidStaticImport .,NL
0,1,"It looks like `QuartzAutoConfiguration` will perform `DataSource` initialization, irrespective of the job store type. This means that an application with a `DataSource` bean that's using an in-memory job store will still have Quartz's DDL applied to the `DataSource`.",NL
0,1,### Issue description,Not
1,1,"I'm trying to get AudioFocus behavior: duck (lower volume) on notifications and pause on incoming call (and play after call end). When i look at the code https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/audio/AudioFocusManager.java#L419 default ExoPlayer implementation should be working like this (or maybe i don't understand it well). But unfortunetely - on incoming call volume is down to 0, but playback doesn't stop.",NL
3,1,Interestingly enough. `CONTENT_TYPE_SPEECH` is not working either. Playback isn't stopped on both - notifications and incoming call.,NL
5,1,### Reproduction steps,Not
6,1,I set audio attributes like this,NL
7,0,```kotlin,Not
8,0,setAudioAttributes(AudioAttributes.Builder(),Not
9,0,.setContentType(C.CONTENT_TYPE_MUSIC),Not
10,0,.setUsage(C.USAGE_MEDIA),Not
11,0,"    .build(), true)",Not
12,0,```,Not
14,1,In logs i can see that `AUDIOFOCUS_LOSS_TRANSIENT` was dispatched. It seems like `PLAYER_COMMAND_WAIT_FOR_CALLBACK` wasn't handled properly.,NL
15,0,```,Not
16,0,D/AudioManager: dispatching onAudioFocusChange(-2) to android.media.AudioManager@1420c8com.google.android.exoplayer2.audio.AudioFocusManager$AudioFocusListener@d3f1561,Not
17,0,D/AudioManager: dispatching onAudioFocusChange(1) to android.media.AudioManager@1420c8com.google.android.exoplayer2.audio.AudioFocusManager$AudioFocusListener@d3f1561,Not
18,0,```,Not
20,1,EDIT: when i digged deeper i found that on `SimpleExoPlayer` `ComponentListener` to `PlayerCommand` is ignoring `PLAYER_COMMAND_WAIT_FOR_CALLBACK` completely,NL
21,0,```java,Not
22,0,private void updatePlayWhenReady(,Not
23,0,"      boolean playWhenReady, @AudioFocusManager.PlayerCommand int playerCommand) {",Not
24,0,player.setPlayWhenReady(,Not
25,0,"        playWhenReady && playerCommand != AudioFocusManager.PLAYER_COMMAND_DO_NOT_PLAY,",Not
26,0,playerCommand != AudioFocusManager.PLAYER_COMMAND_PLAY_WHEN_READY);,Not
27,0,},Not
28,0,```,Not
30,1,### Version of ExoPlayer being used,NL
31,1,2.10.3,Not
33,1,### Device(s) and version(s) of Android being used,NL
34,1,"Samsung Galaxy S7 Edge, Android 8.0; Huawei Mate 20 lite, Android 8.1; Samsung Galaxy A7 (2018), Android 9",Not
36,1,"Also emulators of Pixel 2 devices using Android 8, 9 and Q (9+)",NL
38,0,<!-- DO NOT DELETE,NL
39,0,validate_template=true,Not
40,0,template_path=.github/ISSUE_TEMPLATE/bug.md,Not
41,0,-->,Not
0,1,**Affects:** 5.1.9.RELEASE,Not
2,1,The entry set returned from the result of calling `HttpHeaders.readOnlyHttpHeaders(HttpHeaders)` does not maintain the original headers' ordering. This is a regression from 5.1.0 that I think was introduced in 5.1.1 in https://github.com/spring-projects/spring-framework/commit/ce7278aaf4f20348862267c2081c20dc5bd77128. I believe the set is unordered due to the use of `Collectors.toSet()` which creats an unordered `Set`:,NL
4,0,https://github.com/spring-projects/spring-framework/blob/1ea6ce72bb3b1139abc370f6dc32c51fc27ae90b/spring-web/src/main/java/org/springframework/http/ReadOnlyHttpHeaders.java#L146,Not
0,1,Which make it very hard to debug issue with sandboxing on OS X.,NL
0,1,Affects all versions of 2.x & 3.x,NL
1,1,An example not working configuration is here:,NL
3,0,```,Not
4,0,<network>,Not
5,0,<join>,Not
6,0,"       <tcp-ip enabled=""""true"""">",Not
7,0,<hostname>host-test</hostname>,Not
8,0,<hostname>host-test2</hostname>,Not
9,0,</tcp-ip>,Not
10,0,</join>,Not
11,0,"     <interfaces enabled=""""true”> ",Not
12,0,<interface>127.0.0.*</interface>,Not
13,0,<interface>10.0.2.*</interface>,Not
14,0,<interface>10.10.1.*</interface>,Not
15,0,<interface>10.0.1.*</interface>,Not
16,0,</interfaces>,Not
17,0,</network>,Not
18,0,```,Not
0,1,environment:,NL
1,1,demo site version 3.1.2-GA,Not
2,1,jboss 7.1.1,Not
3,1,tomcat 6,NL
4,1,postgresql 9,NL
6,1,"generated demo site work perfect on tomcat, the same war files deployed on jboss does not work:",NL
7,1,"site war show blank page, nothing in the log",NL
8,1,admin war throw exception,NL
9,1,Caused by: java.lang.NullPointerException,Not
10,0,at org.broadleafcommerce.openadmin.server.service.persistence.PersistenceManagerFactory.getPersistenceManager(PersistenceManagerFactory.java:51) [broadleaf-open-admin-platform-3.1.2-GA.jar:],Not
11,1,the reason: spring application context was not set,NL
13,1,3.1.1-GA work well on jboss 7.1.1,NL
0,1,"When creating a new workspace, a growl type message is shown in the ui saying 'Workspace undefined successfully created'.  I assume this should say 'Workspace -name- successfully created'.",NL
0,0,``` diff,Not
1,0,--- plugin.bat.orig     2011-06-06 21:57:50 +0100,Not
2,0,+++ plugin.bat  2011-06-06 21:57:27 +0100,Not
3,0,"@@ -8,7 +8,7 @@",Not
4,0," for %%I in (""""%SCRIPT_DIR%.."""") do set ES_HOME=%%~dpfI",Not
7,0,"-set ES_CLASSPATH=$CLASSPATH;""""%ES_HOME%/lib/*""""",Not
8,0,+set ES_CLASSPATH=%CLASSPATH%;%ES_HOME%/lib/*,Not
9,0," set ES_PARAMS=-Delasticsearch -Des.path.home=""""%ES_HOME%""""",Not
11,0," """"%JAVA_HOME%\bin\java"""" %JAVA_OPTS% %ES_JAVA_OPTS% %ES_PARAMS% -cp """"%ES_CLASSPATH%"""" """"org.elasticsearch.plugins.PluginManager"""" %*",Not
12,0,```,Not
0,1,"As discussed [here](https://discuss.graphhopper.com/t/calculating-time-should-not-require-to-read-speed-from-edge-in-wrong-direction/509/9), there are cases that result in an Exception using the CurvatureWeighting.",NL
2,1,"Interesting is that in these cases the speed for that edge is 0, but we never set an edge to speed 0 using the getSpeed() method in the CarEncoder.",NL
4,1,The weighting returns 0. And we get the following Exception:,NL
6,0,```,Not
7,0,"java.lang.IllegalStateException: Calculating time should not require to read speed from edge in wrong direction. Reverse:false, fwd:false, bwd:true",NL
8,0,at com.graphhopper.routing.Path.calcMillis(Path.java:266),Not
9,0,at com.graphhopper.routing.Path.processEdge(Path.java:238),Not
10,0,at com.graphhopper.routing.PathBidirRef.extract(PathBidirRef.java:95),Not
11,0,at com.graphhopper.routing.DijkstraBidirectionRef.extractPath(DijkstraBidirectionRef.java:132),Not
12,0,at com.graphhopper.routing.AbstractBidirAlgo.calcPath(AbstractBidirAlgo.java:64),Not
13,0,at com.graphhopper.routing.AbstractRoutingAlgorithm.calcPaths(AbstractRoutingAlgorithm.java:121),Not
14,0,at com.graphhopper.GraphHopper.calcPaths(GraphHopper.java:1327),Not
15,0,```,Not
17,1,"To reproduce this Exception, load the current germany.osm.pbf. And visit this URL: http://localhost:8989/?point=48.873748%2C8.412781&point=49.099864%2C7.993197&locale=de-DE&vehicle=motorcycle&weighting=curvature&elevation=false&layer=Omniscale",NL
0,1,"A small update within the method `CalendarText.isRTL(Locale)` is needed for language codes """"sd"""" and """"ug"""". This is in agreement with an analysis of actual CLDR data.",NL
0,1,### Expected behavior,Not
1,1,Success,NL
3,1,### Actual behavior,Not
4,0,```,Not
5,0,Caused by: java.lang.NullPointerException,Not
6,0,	at reactor.core.publisher.Hooks.onEachOperator(Hooks.java:100),Not
7,0,	at reactor.core.publisher.Hooks.onEachOperator(Hooks.java:69),Not
8,0,	at reactor.core.publisher.Hooks.<clinit>(Hooks.java:476),Not
9,0,```,Not
11,1,### Steps to reproduce,NL
12,1,"1. `Mono.just(""""hello"""").subscribe()`",Not
13,1,2. settings `-Dreactor.trace.operatorStacktrace=true`,Not
14,1,3. Running programs,NL
16,1,### Reactor Core version,Not
17,1,`reactor-core:3.1.2.RELEASE`,Not
19,1,### JVM version (e.g. `java -version`),Not
20,1,`jdk1.8.0_121`,Not
22,1,### OS version (e.g. `uname -a`),Not
23,1,`Windows`,Not
25,1,Initialization of variable order problems,NL
26,0,[Hooks.java#L471](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/Hooks.java#L471),Not
28,0,[Hooks.java#L516](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/Hooks.java#L516),Not
30,1,"Initialization `globalTrace`  `log` The instance has not been created yet, cause `NullPointerException`",NL
0,1,It is very simply to reproduce the issue:,NL
1,1,1. ```,Not
2,1,"     Download 1.7.8, 2.0.6 community edition from: http://orientdb.com/download/",Not
3,0,```,Not
4,1,2. ```,Not
5,1,Run console: ../orientdb-community-1.7.8/bin/console.bat,Not
6,0,```,Not
8,1,create database plocal:C:/OrientDB/orientdb-community-1.7.8/databases/test01 admin admin;,Not
10,1,create database plocal:C:/OrientDB/orientdb-community-1.7.8/databases/test02 admin admin;,Not
11,1,1. ```,Not
12,1,Run  ../orientdb-community-1.7.8/bin/dserver.bat notice server start with no exception. Stop it.,NL
13,0,```,Not
14,1,2. ```,Not
15,1,Copy directory: orientdb-community-1.7.8/databases into: ../orientdb-community-2.0.6/databases,Not
16,0,```,Not
17,1,3. ```,Not
18,1,Run  ../orientdb-community-2.0.6/bin/dserver.bat notice exception:,NL
19,1,```,Not
21,0,2015-04-10 14:29:10:306 INFO  [node1428684304423] adding node 'node1428684304423' in partition: db=t,Not
22,0,est02 [*] [OHazelcastDistributedDatabase],Not
23,0,2015-04-10 14:29:10:308 WARNING Error deserializing record YXV0b0RlcGxveTp0cnVlLGhvdEFsaWdubWVudDpmY,Not
24,0,WxzZSxyZWFkUXVvcnVtOjEsd3JpdGVRdW9ydW06MixmYWlsdXJlQXZhaWxhYmxlTm9kZXNMZXNzUXVvcnVtOmZhbHNlLHJlYWRZb,Not
25,0,3VyV3JpdGVzOnRydWUsY2x1c3RlcnM6KGludGVybmFsOigpLGluZGV4OigpLCo6KHNlcnZlcnM6WyI8TkVXX05PREU+Iiwibm9kZ,Not
26,0,TE0Mjg2OTM2OTEzMzYiXSkpLHZlcnNpb246MA== send this data for debugging [ORecordSerializerBinary][10.12,Not
27,0,5.3.47]:2434 [orientdb] [3.3] hz._hzInstance_1_orientdb.event-2 caught an exception while processing,Not
28,0,task:com.hazelcast.spi.impl.EventServiceImpl$LocalEventDispatcher@e968b45,Not
29,0,java.lang.ArrayIndexOutOfBoundsException: 97,Not
30,0,at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerialize,Not
31,0,rBinary.fromStream(ORecordSerializerBinary.java:72),Not
32,0,at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:,NL
33,0,1755),Not
34,0,at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:218,Not
35,0,7),Not
36,0,at com.orientechnologies.orient.core.record.impl.ODocument.rawField(ODocument.java:834),Not
37,0,at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:854),Not
38,0,at com.orientechnologies.orient.server.distributed.ODistributedAbstractPlugin.updateCachedDa,Not
39,0,tabaseConfiguration(ODistributedAbstractPlugin.java:220),Not
40,0,at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.updateCachedDatabaseConfig,Not
41,0,uration(OHazelcastPlugin.java:780),Not
42,0,at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.checkDatabaseEvent(OHazelc,Not
43,0,astPlugin.java:1070),Not
44,0,at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.entryAdded(OHazelcastPlugi,Not
45,0,n.java:607),Not
46,0,at com.hazelcast.map.MapEventPublishingService.dispatch0(MapEventPublishingService.java:85),Not
47,0,at com.hazelcast.map.MapEventPublishingService.dispatchEntryEventData(MapEventPublishingServ,Not
48,0,ice.java:64),Not
49,0,at com.hazelcast.map.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:,Not
50,0,39),Not
51,0,at com.hazelcast.map.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:,Not
52,0,17),Not
53,0,at com.hazelcast.map.MapService.dispatchEvent(MapService.java:76),Not
54,0,at com.hazelcast.map.MapService.dispatchEvent(MapService.java:51),Not
55,0,at com.hazelcast.spi.impl.EventServiceImpl$LocalEventDispatcher.run(EventServiceImpl.java:65,Not
56,0,8),Not
57,0,at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:189),Not
58,0,at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:173),Not
60,0,2015-04-10 14:29:10:320 WARNING [node1428684304423] updated distributed configuration for database:,NL
61,0,test02:,NL
63,1,"Thanks,",NL
64,1,Vasil,NL
0,1,Hi there!,NL
2,1,I spotted something that might be wrong with the OSX `.gitgnore` template.,NL
4,1,Here is the generated file I've got:,NL
6,0,```,Not
7,0,# Created by .ignore support plugin (hsz.mobi),NL
9,0,### OSX template,Not
10,0,.DS_Store,Not
11,0,.AppleDouble,Not
12,0,.LSOverride,Not
14,0,# Icon must end with two \r,NL
15,0,Icon,NL
17,0,# Thumbnails,NL
18,0,._*,Not
20,0,# Files that might appear in the root of a volume,NL
21,0,.DocumentRevisions-V100,Not
22,0,.fseventsd,Not
23,0,.Spotlight-V100,Not
24,0,.TemporaryItems,Not
25,0,.Trashes,Not
26,0,.VolumeIcon.icns,Not
28,0,# Directories potentially created on remote AFP share,NL
29,0,.AppleDB,Not
30,0,.AppleDesktop,Not
31,0,Network Trash Folder,NL
32,0,Temporary Items,NL
33,0,.apdisk,Not
34,0,```,Not
36,1,The error lies here:,NL
38,0,```,Not
39,0,# Icon must end with two \r,NL
40,0,Icon,NL
41,0,```,Not
43,1,"Actually, it seems that there're 2 `\0` characters instead of 2 `\r`, which might break things [as I ran into some issues with git-related tools](http://forums.gitup.co/t/unhandled-character-in-gitignore/278).",NL
45,1,I'm not sure it was expected so I'm reporting as it looks like an issue.,NL
47,1,"For comparison, here is the diff with the http://www.gitignore.io version (which is on the left):",NL
49,0,![capture d ecran 2015-07-30 a 09 05 02](https://cloud.githubusercontent.com/assets/1094774/8977538/54e0039c-369a-11e5-8ffc-0402ba7544c8.png),Not
51,1,Thanks a lot for your useful plugin by the way :+1:,NL
0,1,from pull #3918 discussion.,NL
2,1,Looks like we have the same problem for ```DEFAULT_TOKEN```. I think that it should be fixed in separate issue.,NL
4,0,````,Not
5,0,$ cat TestClass.java,Not
6,0,public class TestClass {,Not
7,0,void method(int a) {,Not
8,0,switch (a) {},Not
9,0,switch (a) {default: },Not
10,0,switch (a) {default: {}} // violation is expected,Not
11,0,switch (a) {,Not
12,0,default:,NL
13,0,},Not
14,0,switch (a) {,Not
15,0,default: // violation is expected,NL
16,0,{},Not
17,0,},Not
18,0,switch (a) {,Not
19,0,default: // violation is expected,NL
20,0,{,Not
21,0,},Not
22,0,},Not
23,0,},Not
24,0,},Not
26,0,$ cat TestConfig.xml,NL
27,0,"<?xml version=""""1.0""""?>",Not
28,0,<!DOCTYPE module PUBLIC,Not
29,0,"          """"-//Puppy Crawl//DTD Check Configuration 1.3//EN""""",Not
30,0,"          """"http://www.puppycrawl.com/dtds/configuration_1_3.dtd"""">",Not
32,0,"<module name=""""Checker"""">",Not
33,0,"    <property name=""""charset"""" value=""""UTF-8""""/>",Not
34,0,"<module name=""""TreeWalker"""">",Not
35,0,"        <module name=""""EmptyBlock"""">",Not
36,0,"            <property name=""""tokens"""" value=""""LITERAL_DEFAULT""""/>",Not
37,0,</module>,Not
38,0,</module>,Not
39,0,</module>,Not
41,0,$ java -jar checkstyle-7.6-all.jar -c TestConfig.xml TestClass.java,Not
42,0,Starting audit...,NL
43,0,Audit done.,NL
44,0,````,Not
0,1,"Hi Team,",NL
1,1," When pre roll ad is playing and app goes in background and comes back in foreground, app crashes. Here is the stack trace.",NL
3,0,`FATAL EXCEPTION: main Process:,NL
4,0,PID: 22373 java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.ads.interactivemedia.v3.api.AdsManager.resume()' on a null object reference at com.google.android.exoplayer2.ext.ima.ImaAdsLoader.attachPlayer(ImaAdsLoader.java:396) at com.google.android.exoplayer2.source.ads.AdsMediaSource$2.run(AdsMediaSource.java:219) at android.os.Handler.handleCallback(Handler.java:789) at android.os.Handler.dispatchMessage(Handler.java:98) at android.os.Looper.loop(Looper.java:164) at android.app.ActivityThread.main(ActivityThread.java:6809) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`,Not
6,1,Here are my onresume and onpause methods of fragment:,NL
7,0,` @Override,Not
8,0,public void onResume() {,Not
9,0,super.onResume();,Not
10,0,"        player.init(getActivity(), playerView);",Not
11,0,}`,Not
14,0,` @Override,Not
15,0,public void onPause() {,Not
16,0,super.onPause();,Not
17,0,player.reset();,Not
18,0,player.release();,Not
19,0,playerView.getPlayer().release();,Not
20,0,}`,Not
22,1,Please help me with the same.,NL
0,1,"In PoolingHttpDestination:process(final C connection, boolean dispatch) a check is performed to ensure the request was not aborted before being associated with a connection and if it was then the connection is neither released or closed. Might be useful to move the connection release code below in a separate method and use it for both cases - i.e. when there's no exchange or the request was aborted prior to creation of the exchange.",NL
2,0,```,Not
3,0,"public void process(final C connection, boolean dispatch)",Not
4,0,{,Not
5,0,HttpClient client = getHttpClient();,Not
6,0,final HttpExchange exchange = getHttpExchanges().poll();,Not
7,0,if (LOG.isDebugEnabled()),NL
8,0,"            LOG.debug(""""Processing exchange {} on {} of {}"""", exchange, connection, this);",Not
9,0,if (exchange == null),Not
10,0,{,Not
11,0,if (!connectionPool.release(connection)),NL
12,0,connection.close();,Not
14,0,if (!client.isRunning()),NL
15,0,{,Not
16,0,if (LOG.isDebugEnabled()),NL
17,0,"                    LOG.debug(""""{} is stopping"""", client);",Not
18,0,connection.close();,Not
19,0,},Not
20,0,},Not
21,0,else,NL
22,0,{,Not
23,0,final Request request = exchange.getRequest();,Not
24,0,Throwable cause = request.getAbortCause();,Not
25,0,if (cause != null),Not
26,0,{,Not
27,0,if (LOG.isDebugEnabled()),NL
28,0,"                    LOG.debug(""""Aborted before processing {}: {}"""", exchange, cause);",Not
29,0,// It may happen that the request is aborted before the exchange,NL
30,0,// is created. Aborting the exchange a second time will result in,NL
31,0,"                // a no-operation, so we just abort here to cover that edge case.",Not
32,0,exchange.abort(cause);,Not
33,0,},Not
34,0,else,NL
35,0,{,Not
36,0,if (dispatch),NL
37,0,{,Not
38,0,client.getExecutor().execute(new Runnable(),Not
39,0,{,Not
40,0,@Override,NL
41,0,public void run(),Not
42,0,{,Not
43,0,"                            send(connection, exchange);",Not
44,0,},Not
45,0,});,Not
46,0,},Not
47,0,else,NL
48,0,{,Not
49,0,"                    send(connection, exchange);",Not
50,0,},Not
51,0,},Not
52,0,},Not
53,0,},Not
54,0,```,Not
0,1,The same column of type INTEGER in raw query can be mapped to Long or to Integer.,NL
2,1,"The problem occurs because type mapping is stored in `Map` class, and the type mapping method:",NL
3,0,https://github.com/requery/requery/blob/14a8ac29a4a97872878ae773fc8c96d3e7c10dbb/requery/src/main/java/io/requery/sql/GenericMapping.java#L249,Not
4,1,Just iterates through that map to get mapped type.,NL
6,1,Types map looks like this:,NL
7,0,```,Not
8,0,"0 = {AbstractMap$SimpleEntry@8270} """"class java.sql.Timestamp"""" -> """"TIMESTAMP""""",Not
9,0,"1 = {AbstractMap$SimpleEntry@8271} """"class java.lang.Boolean"""" -> """"BOOLEAN""""",Not
10,0,"2 = {AbstractMap$SimpleEntry@8272} """"class java.lang.String"""" -> """"VARCHAR(255)""""",Not
11,0,"3 = {AbstractMap$SimpleEntry@8273} """"class java.math.BigDecimal"""" -> """"DECIMAL""""",Not
12,0,"4 = {AbstractMap$SimpleEntry@8274} """"float"""" -> """"FLOAT""""",Not
13,0,"5 = {AbstractMap$SimpleEntry@8275} """"class java.lang.Double"""" -> """"REAL""""",Not
14,0,"6 = {AbstractMap$SimpleEntry@8276} """"interface java.sql.Blob"""" -> """"BLOB""""",Not
15,0,"7 = {AbstractMap$SimpleEntry@8277} """"interface java.sql.Clob"""" -> """"CLOB""""",Not
16,0,"8 = {AbstractMap$SimpleEntry@8278} """"class java.lang.Byte"""" -> """"TINYINT""""",Not
17,0,"9 = {AbstractMap$SimpleEntry@8279} """"short"""" -> """"SMALLINT""""",Not
18,0,"10 = {AbstractMap$SimpleEntry@8280} """"class java.lang.Short"""" -> """"SMALLINT""""",Not
19,0,"11 = {AbstractMap$SimpleEntry@8281} """"class [B"""" -> """"VARBINARY(null)""""",Not
20,0,"12 = {AbstractMap$SimpleEntry@8282} """"class java.sql.Date"""" -> """"DATE""""",Not
21,0,"13 = {AbstractMap$SimpleEntry@8283} """"int"""" -> """"INTEGER""""",Not
22,0,"14 = {AbstractMap$SimpleEntry@8284} """"class java.lang.Integer"""" -> """"INTEGER""""",Not
23,0,"15 = {AbstractMap$SimpleEntry@8285} """"class java.lang.Long"""" -> """"INTEGER""""",Not
24,0,"16 = {AbstractMap$SimpleEntry@8286} """"boolean"""" -> """"BOOLEAN""""",Not
25,0,"17 = {AbstractMap$SimpleEntry@8287} """"class java.lang.Float"""" -> """"FLOAT""""",Not
26,0,"18 = {AbstractMap$SimpleEntry@8288} """"long"""" -> """"INTEGER""""",Not
27,0,"19 = {AbstractMap$SimpleEntry@8289} """"byte"""" -> """"TINYINT""""",Not
28,0,"20 = {AbstractMap$SimpleEntry@8290} """"class java.sql.Time"""" -> """"TIME""""",Not
29,0,"21 = {AbstractMap$SimpleEntry@8291} """"double"""" -> """"REAL""""",Not
30,0,"22 = {AbstractMap$SimpleEntry@8292} """"class java.util.Date"""" -> """"DATE""""",Not
31,0,```,Not
32,1,"So, you see - SQL INTEGER type corresponds to Long and to Integer java types.",NL
34,1,"As `Map` does not guarantee consistent iteration order, we get different results in different situations - at least, the same code on API-22 returns Integer, while on API-19 - Long. Maybe there are other factors.",NL
36,1,So it's impossible to use raw queries with `Long` or `Integer` fields - app just crashes because of incompatible types.,NL
38,1,P.S. for now my work-around was to use custom Mapping class.,NL
0,1,I have a Boot application that has a servlet filter to apply CORS headers to responses in certain scenarios.,NL
2,1,"In 1.1.4, when I make an OPTIONS call to my application, I get the response I'm expecting.",NL
4,1,"In 1.1.5, the CORS headers I'm expecting are missing, and no exception is generated in the logs. However, if I look at the `/manage/trace` endpoint, I see two things: 1) the OPTIONS request for some reason is returning an HTTP status of """"0""""; 2) the server is sending an error and the trace has a stack in it.",NL
6,1,Can someone help me understand why an HTTP status code of 0 is being returned?,NL
8,1,"Also, the code in 1.1.5 for `MetricFilterAutoConfiguration` has a change that does not gracefully handle the 0 status, while the code in 1.1.4 does handle it.",NL
10,1,Here is the stack that I found in the trace endpoint:,NL
12,0,```,Not
13,0,java.lang.IllegalArgumentException: No matching constant for [0],NL
14,0,at org.springframework.http.HttpStatus.valueOf(HttpStatus.java:467),Not
15,0,at org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration$MetricsFilter.doFilterInternal(MetricFilterAutoConfiguration.java:99),Not
16,0,at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107),Not
17,0,at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1480),Not
18,0,at org.springframework.boot.context.web.ErrorPageFilter.doFilter(ErrorPageFilter.java:108)\n\tat,Not
19,0,```,Not
0,1,A corrupt ICC header may cause java.awt.color.ICC_Profile to allocate a huge read buffer resulting in an OutOfMemory exception. You may want to catch this in the TIFFImageReader.getICCProfile() like this:,NL
2,0,catch (CMMException | IllegalArgumentException | **OutOfMemoryError** ignore) {,Not
3,0,"        processWarningOccurred(""""Ignoring broken/incompatible ICC profile: """" + ignore.getMessage());",Not
4,0,},Not
0,1,"The `query_string` query has `<` and `>` operators that make it easy to build range queries. For instance, `age:>18` is equivalent to `age:{18 TO *]`. The issue however is that given that it is implemented on top of the base Lucene query parser (`<` and `>` are handled in `MapperQueryParser#getFieldQuerySingle`), they cannot be escaped like other query operators. So if you want to search for a term that starts with `<` or `>` in a `keyword` field, the only way to do so is to quote the searched term, eg. `my_field:"""">value""""`.",NL
0,1,I use Elasticsearch with Logstash and dynamic mapping.,NL
1,1,"I my logs, I have geopoints with the array syntax.",NL
2,1,"It was OK with ES 1.0.X, but it's broken with ES 1.2.2.",NL
4,1,Template:,NL
6,0,```,Not
7,0,curl -XPUT localhost:9200/_template/logstash -d '{,Not
8,0,"    """"template"""": """"logstash_*"""",",Not
9,0,"    """"settings"""" : {",Not
10,0,"        """"refresh_interval"""": """"30s""""",Not
11,0,"    },",NL
12,0,"    """"mappings"""": {",Not
13,0,"        """"logs"""": {",Not
14,0,"            """"_all"""" : {",Not
15,0,"                """"enabled"""": false",Not
16,0,"            },",Not
17,0,"            """"dynamic_templates"""": [",Not
18,0,{,Not
19,0,"                    """"location"""": {",Not
20,0,"                        """"match"""": """"location*"""",",Not
21,0,"                        """"mapping"""": {",Not
22,0,"                            """"type"""": """"geo_point""""",Not
23,0,},Not
24,0,},Not
25,0,"                },",Not
26,0,{,Not
27,0,"                    """"generic"""": {",Not
28,0,"                        """"match"""": """"*"""",",Not
29,0,"                        """"match_mapping_type"""": """"string"""",",Not
30,0,"                        """"mapping"""": {",Not
31,0,"                            """"type"""": """"string"""",",Not
32,0,"                            """"index"""": """"not_analyzed""""",Not
33,0,},Not
34,0,},Not
35,0,},Not
36,0,"            ],",Not
37,0,"            """"dynamic_date_formats"""": [",Not
38,0,"                """"dateOptionalTime"""",",Not
39,0,"                """"yyyy-MM-dd"""",",Not
40,0,"                """"yyyy-MM-dd HH:mm:ss""""",Not
41,0,],Not
42,0,},Not
43,0,},Not
44,0,}',Not
45,0,```,Not
47,1,Delete index:,NL
49,0,```,Not
50,0,curl -XDELETE localhost:9200/logstash_test,Not
51,0,```,Not
53,1,Try to add a doc/log:,NL
55,0,```,Not
56,0,curl -XPOST localhost:9200/logstash_test/logs -d '{,Not
57,0,"  """"location_array"""": [",Not
58,0,"    2.3069244,",Not
59,0,48.8881598,Not
60,0,],Not
61,0,}',Not
62,0,```,Not
64,1,It fails with this message:,NL
66,0,```,Not
67,0,"[2014-07-21 11:31:49,168][INFO ][cluster.metadata         ] [fr-dev-01] [logstash_test] creating index, cause [auto(index api)], shards [5]/[1], mappings [logs]",Not
68,0,"[2014-07-21 11:31:49,465][DEBUG][action.index             ] [fr-dev-01] [logstash_test][1], node[zzMEQe9JSS6qEgw0oRgdVA], [P], s[STARTED]: Failed to execute [index {[logstash_test][logs][PhqP9fpgQkS4tHfOs105GQ], source[{""""location_array"""":[2.3069244,48.8881598]}]}]",Not
69,0,org.elasticsearch.index.mapper.MapperParsingException: failed to parse,NL
70,0,at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:536),Not
71,0,at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:462),Not
72,0,at org.elasticsearch.index.shard.service.InternalIndexShard.prepareCreate(InternalIndexShard.java:373),Not
73,0,at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:203),Not
74,0,at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:534),Not
75,0,at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:433),Not
76,0,at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145),Not
77,0,at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615),Not
78,0,at java.lang.Thread.run(Thread.java:724),Not
79,0,Caused by: org.elasticsearch.ElasticsearchParseException: geo_point expected,Not
80,0,at org.elasticsearch.common.geo.GeoUtils.parseGeoPoint(GeoUtils.java:421),Not
81,0,at org.elasticsearch.index.mapper.geo.GeoPointFieldMapper.parse(GeoPointFieldMapper.java:530),Not
82,0,at org.elasticsearch.index.mapper.object.ObjectMapper.parseDynamicValue(ObjectMapper.java:819),Not
83,0,at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:639),Not
84,0,at org.elasticsearch.index.mapper.object.ObjectMapper.serializeArray(ObjectMapper.java:625),Not
85,0,at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:482),Not
86,0,at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:515),Not
87,0,... 8 more,NL
88,0,```,Not
90,1,"If I insert a doc with a geopoint as an object, it works, and the mapping is created dynamically.",NL
91,1,"After that, I can insert a doc with a geopoint as an array without error.",NL
0,0,'/var/tmp $ javac Test.java':,Not
2,0,`/var/tmp $ cat Test.java`:,Not
4,0,```,Not
5,0,/*,Not
6,0,-----------------------------------------------------------------------------------,Not
8,0,example,NL
10,0,Copyright (c) 2001-2018 XXX,Not
12,0,-----------------------------------------------------------------------------------,Not
13,0,*/,Not
15,0,public class Test {,Not
17,0,public Test() {,Not
18,0,},Not
19,0,},Not
20,0,```,Not
22,0,`/var/tmp $ cat checkstyle.header`:,NL
24,0,```,Not
25,0,/*,Not
26,0,-----------------------------------------------------------------------------------,Not
28,0,example,NL
30,0,Copyright (c) 2001-2018 XXX,Not
32,0,-----------------------------------------------------------------------------------,Not
33,0,*/,Not
34,0,```,Not
36,0,`/var/tmp $ cat config.xml`:,NL
38,0,```,Not
39,0,"<?xml version=""""1.0"""" encoding=""""ISO-8859-1""""?>",Not
41,0,<!DOCTYPE module PUBLIC,Not
42,0,"    """"-//Puppy Crawl//DTD Check Configuration 1.3//EN""""",Not
43,0,"    """"http://www.puppycrawl.com/dtds/configuration_1_3.dtd"""">",Not
45,0,"<module name=""""Checker"""">",Not
46,0,"  <module name=""""Header"""">",Not
47,0,"    <property name=""""headerFile"""" value=""""checkstyle.header""""/>",Not
48,0,"    <property name=""""fileExtensions"""" value=""""java""""/>",Not
49,0,</module>,Not
50,0,</module>,Not
51,0,```,Not
53,0,`/var/tmp $ java -Duser.language=en -Duser.country=US -jar checkstyle-8.8-all.jar -c config.xml Test.java`:,Not
55,0,```,Not
56,0,"Feb 05, 2018 8:00:11 PM com.puppycrawl.tools.checkstyle.Main runCli",Not
57,0,FINE: Checkstyle debug logging enabled,NL
58,0,"Feb 05, 2018 8:00:11 PM com.puppycrawl.tools.checkstyle.Main runCli",Not
59,0,FINE: Running Checkstyle with version: 8.8,NL
60,0,Starting audit...,NL
61,0,[ERROR] /data1/home/martin/x_checkstyle/Test.java:3: Line does not match expected header line of '^$'. [Header],Not
62,0,Audit done.,NL
63,0,Checkstyle ends with 1 errors.,NL
64,0,```,Not
66,0,---------------,Not
68,1,I found this issue upgrading from version 6.7 to 8.8.,NL
69,1,The Header check does not match the empty lines like expected.,NL
70,1,"Looking through the CheckStyle source I would guess that the AbstractHeaderCheck method loadHeader is converting empty lines to """"^$"""" what cannot work with the equals in the HeaderCheck isMatch method.",NL
0,1,"A few days ago I noticed that my websocket clients are being disconnected in weird way. I found that, when upgrade is complete, exception below is being thrown from HttpResponseDecoder and WebSocketClientProtocolHandler just closes connection on exception. And this happens only if i use pooled allocator for channels.",NL
2,0,```,Not
3,0,io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0,Not
4,0,at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:391),Not
5,0,at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244),Not
6,0,at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318),Not
7,0,at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304),Not
8,0,at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846),Not
9,0,at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131),Not
10,0,at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511),Not
11,0,at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468),Not
12,0,at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382),Not
13,0,at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354),Not
14,0,at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112),Not
15,0,at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137),Not
16,0,at java.lang.Thread.run(Thread.java:745),Not
17,0,Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0,Not
18,0,at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1190),Not
19,0,at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1176),Not
20,0,at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1172),Not
21,0,at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:672),Not
22,0,at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:390),Not
23,0,at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:360),Not
24,0,... 12 more,NL
25,0,```,Not
27,1,System info,NL
29,0,```,Not
30,1,Linux Atplaychannel 3.5.0-17-generic #28-Ubuntu SMP Tue Oct 9 19:31:23 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux,Not
31,0,```,Not
33,1,Java version,NL
35,0,```,Not
36,1,"java version """"1.8.0_66""""",Not
37,1,Java(TM) SE Runtime Environment (build 1.8.0_66-b17),Not
38,1,"Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)",Not
39,0,```,Not
41,1,This happens only when first websocket frame is being received in same packet as upgrade response.,NL
42,1,Netty version is 4.0.33.Final and it looks like that previous versions don't have this issue.,NL
44,1,Code that reproduces the issue https://gist.github.com/lexek/b61d0980f029f47b353b,NL
0,1,The plugin script now will automatically download plugins from `download.elasticsearch.org` instead of github. It will also try maven (both central and sonatype) if it fails.,NL
2,1,"Effectively, this change removes the ability to install plugins from the downloads section in github, since its no longer supported by github. Site plugins can still be installed by downloading the """"repo"""".",NL
4,1,"Direct installation is still supported, using the `bin/plugin -url file://path/to/plugin -name plugin-name`.",NL
0,1,### Expected behavior,Not
1,1,No null pointer exceptions,NL
3,1,### Actual behavior,Not
4,1,"When an HTTP/1.1 upgrade request comes in, we call `onHttpServerUpgrade` in Http2ConnectionHandler.  This makes us create a stream, which eventually calls `new DefaultHttp2StreamChannel`, which is fine, except that it assumes that handlerAdded has already been called on Http2MultiplexCodec . . . which is always true except when we're doing a cleartext upgrade.",NL
6,1,### Steps to reproduce,NL
8,1,"Make an HttpServerUpgradeHandler, with an Http2MultiplexCodec.  Send an h2c upgrade request.",NL
10,1,### Minimal yet complete reproducer code (or URL to code),Not
12,1,Try to upgrade this to netty 4.1.15.,NL
14,0,https://github.com/twitter/finagle/blob/develop/finagle-http2/src/main/scala/com/twitter/finagle/http2/Http2CleartextServerInitializer.scala#L74,Not
16,1,### Netty version,Not
17,1,4.1.15.Final,Not
0,1,Following on from issue #8314 if I attempt to set management.security.roles to an array using the config below I get an `UnsupportedOperationException` thrown from `java.util.AbstractList#add` for the second element,NL
2,0,```,Not
3,0,management:,NL
4,0,context-path: /management,Not
5,0,security:,NL
6,0,enabled: true,Not
7,0,roles:,NL
8,0,"    - CN=some-group,OU=somewhere,OU=in,OU=ldap,DC=example,DC=com",Not
9,0,"    - CN=some-other-group,OU=somewhere,OU=in,OU=ldap,DC=example,DC=com",Not
10,0,```,Not
12,1,I have updated https://github.com/jonfreedman/spring-boot-management-demo to illustrate,NL
0,1,"Just as an information, when I start the app with the most current version of Realm I get the following log messages:",NL
2,0,```,Not
3,0,I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$4>,Not
4,0,I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$4>,Not
5,0,I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$3>,Not
6,0,I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$3>,Not
7,0,I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$2>,Not
8,0,I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$2>,Not
9,0,I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$1>,Not
10,0,I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$1>,Not
11,0,```,Not
13,1,"We are currently not using the new `rx`feature, but just wanted to see if this is something to be concerned about.",NL
15,1,The device was a Nexus 5 running Android 6.,NL
0,1,"In the `org.springframework.boot.autoconfigure.jmx.ParentAwareNamingStrategy.getObjectName(Object, String)` method the contents of the `StringBuilder` builder variable are updated, but never queried.",NL
0,1,"The distributed map seems to loose data, when you try to put an already mapped key into the map after another member has been started. I found this behaviour in the Version 2.0.2 and 2.1 snapshot build. Didn't try any 1.x version. I am using two Win7 64 Bit machines with jdk 1.7u3.",NL
2,1,Steps to reproduce the problem:,NL
3,1,- Start one hazelcast server,NL
4,1,- Fill a map with some simple data:,NL
6,0,``` java,Not
7,0,public static void main(String[] args) {,Not
8,0,int startKey = 0;,Not
9,0,int numberOfKeys = 10;,Not
10,0,Random rand = new Random();,Not
11,0,ClientConfig clientConfig = new ClientConfig();,Not
12,0,"        clientConfig.getGroupConfig().setName(""""dev"""").setPassword(""""dev-pass"""");",Not
13,0,clientConfig.addAddress(Globals.serverNames);,Not
14,0,HazelcastInstance client = HazelcastClient.newHazelcastClient(clientConfig);,Not
16,0,"        IMap<Long, Long> myMap = client.getMap(""""mydata"""");",Not
17,0,for (int i = startKey; i < (startKey+numberOfKeys); i++) {,Not
18,0,Long key = new Long(i);,Not
19,0,myMap.lock(key);,Not
20,0,"            myMap.put(key, new Long(rand.nextInt()));",Not
21,0,myMap.unlock(key);,Not
22,0,System.out.println(new Long(i).toString());,Not
23,0,},Not
24,0,myMap.flush();,Not
25,0,System.out.println(myMap.size());,Not
26,0,client.getLifecycleService().shutdown();,Not
28,0,},Not
29,0,```,Not
30,1,- List the keys of the map:,NL
32,0,``` java,Not
33,0,public static void main(String[] args) {,Not
35,0,ClientConfig clientConfig = new ClientConfig();,Not
36,0,"        clientConfig.getGroupConfig().setName(""""dev"""").setPassword(""""dev-pass"""");",Not
37,0,clientConfig.addAddress(Globals.serverNames);,Not
38,0,HazelcastInstance client = HazelcastClient.newHazelcastClient(clientConfig);,Not
39,0,PartitionService partitionService = client.getPartitionService();,Not
41,0,"        Map<Long, Long> myMap = client.getMap(""""mydata"""");",Not
42,0,Set keys = myMap.keySet();,Not
44,0,Iterator<Long> iter = keys.iterator();,Not
45,0,int counter = 0;,Not
46,0,while (iter.hasNext()) {,Not
47,0,Long t  = iter.next();,Not
48,0,Partition partition = partitionService.getPartition(t);,Not
49,0,Member ownerMember = partition.getOwner();,Not
50,0,"            System.out.println(t + """";"""" + ownerMember.toString());",Not
51,0,counter++;,Not
52,0,},Not
53,0,"        System.out.println(""""Number of keys: """" + counter);",Not
54,0,client.getLifecycleService().shutdown();,Not
55,0,},Not
56,0,```,Not
58,1,Output:,NL
60,0,```,Not
61,0,0;Member [192.168.0.4]:5701,Not
62,0,1;Member [192.168.0.4]:5701,Not
63,0,2;Member [192.168.0.4]:5701,Not
64,0,3;Member [192.168.0.4]:5701,Not
65,0,4;Member [192.168.0.4]:5701,Not
66,0,5;Member [192.168.0.4]:5701,Not
67,0,6;Member [192.168.0.4]:5701,Not
68,0,7;Member [192.168.0.4]:5701,Not
69,0,8;Member [192.168.0.4]:5701,Not
70,0,9;Member [192.168.0.4]:5701,Not
71,0,Number of keys: 10,NL
72,0,```,Not
73,1,- Start a second hazelcast server,NL
74,1,- List the keys again:,NL
75,1,Output:,NL
77,0,```,Not
78,0,0;Member [192.168.0.4]:5701,Not
79,0,1;Member [192.168.0.4]:5701,Not
80,0,2;Member [192.168.0.5]:5701,Not
81,0,3;Member [192.168.0.4]:5701,Not
82,0,4;Member [192.168.0.4]:5701,Not
83,0,5;Member [192.168.0.5]:5701,Not
84,0,6;Member [192.168.0.4]:5701,Not
85,0,7;Member [192.168.0.4]:5701,Not
86,0,8;Member [192.168.0.5]:5701,Not
87,0,9;Member [192.168.0.5]:5701,Not
88,0,Number of keys: 10,NL
89,0,```,Not
91,1,Some of the keys have changed ownership - just as expected.,NL
92,1,- Now run the code the fill the map again.,NL
93,1,- List the keys again:,NL
95,1,Output:,NL
97,0,```,Not
98,0,0;Member [192.168.0.4]:5701,Not
99,0,1;Member [192.168.0.4]:5701,Not
100,0,3;Member [192.168.0.4]:5701,Not
101,0,4;Member [192.168.0.4]:5701,Not
102,0,6;Member [192.168.0.4]:5701,Not
103,0,7;Member [192.168.0.4]:5701,Not
104,0,Number of keys: 6,NL
105,0,```,Not
107,1,"All the migrated keys are missing. When setting the log level to finest, the second hazelcast server tells me, that it is evicting 4 entries. If you run the code to fill the map again, everything will be fine. I tried it with a lot of different map properties - none seem to solve this problem. Changes to the code (for example setting the ttl with put, setting a lock on the map, using replace instead of put for second mapping) didn't help.",NL
0,1,**Describe the bug**,NL
1,1,"escape/unescape fails with string mode """"javascript""""",NL
3,1,**To Reproduce**,Not
4,1,"Start with the letter """"Ä"""" as cell value",NL
6,1,"escape/unescape works fine using string mode """"html""""",NL
8,0,"Ä > escape(value, """"html"""") > &Auml; > unescape(value, """"html"""") > Ä",Not
10,1,"But it fails when using string mode """"javascript""""",NL
12,0,"Ä > escape(value, """"javascript"""") > \u00C4 > unescape(value, """"javascript"""") > \\\u00C4",Not
14,1,**Current Results**,Not
15,1,unescape does not reverse escape,NL
17,1,**Expected behavior**,Not
18,1,unescape should reverse escape,NL
20,1,**Desktop (please complete the following information):**,NL
21,1,- OS: Windows,Not
22,1,- Browser chrome,NL
23,1,- Version 67.0.3396.99,Not
25,1,**OpenRefine (please complete the following information):**,NL
26,1,- Version OpenRefine 3.0 Beta,NL
0,1,I have observed that if you have multiple scenarios in a feature and you run the scenarios in parallel then you can (quite reliably) get a wrong karate.tagValues in your scenario.,NL
2,1,I have attached a minimal project where this issue can be reproduced: [paralleltags.zip](https://github.com/intuit/karate/files/2782951/paralleltags.zip).,NL
4,1,"If you execute the SequentialRunner then all tests pass as expected, but with the ParallelRunner they don't. Sometimes tests run fine with the ParallelRunner, so I suspect there is a race condition somewhere.",NL
6,1,Please let me know should you need any more information.,NL
0,1,The spring plugin overlaps with the enterprise spring plugin and is not maintained properly. We should remove the OSS Spring plugin and only use the Enterprise Spring plugin.,NL
0,1,"When the config model is loaded from a JSON file, the tree gets updated but the underlying HashMap is not. The result of this is that the JSON file that is created when the project is saved lacks many of the fields. The problem is not apparent since the observable model is correct, it is only the underlying map that is incorrect.",NL
2,1,**Steps to reproduce:**,NL
3,1,1. Create a new project and open UI (works),NL
4,1,2. Connect to database and generate code (works),NL
5,1,3. Close UI and open it again so that the JSON file is loaded (here is where something happens),NL
6,1,4. Generate code again (the generated .json-file is wrong),NL
8,1,"The settings are loaded into the JavaFX-components correctly, but when the map is passed to the generator, it looks like it is an old version of the map.",NL
10,1,This issue only exists in the current `develop` branch.,NL
0,1,### OrientDB Version: v3.0.3,Not
1,1,### Java Version: 8,Not
2,1,### OS: macOS High Sierra,Not
4,1,## Expected behavior,NL
5,1,On issuing update edge command the endpoint should update.  This worked in v2.2.35 but its not working in v3.0.3.,NL
7,1,## Actual behavior,NL
8,1,It's throwing a error saying out is not a vertex and is failing on validateOutInForEdge.,NL
10,0,`com.orientechnologies.orient.core.exception.OCommandExecutionException: Error updating edge: 'out' is not a vertex - [V#9:0{name:a} v1],Not
11,0,"	DB name=""""test""""",Not
12,0,	at com.orientechnologies.orient.core.sql.executor.UpdateEdgePointersStep.validateOutInForEdge(UpdateEdgePointersStep.java:126),Not
13,0,	at com.orientechnologies.orient.core.sql.executor.UpdateEdgePointersStep.handleUpdateEdge(UpdateEdgePointersStep.java:86),Not
14,0,	at com.orientechnologies.orient.core.sql.executor.UpdateEdgePointersStep.access$000(UpdateEdgePointersStep.java:16),Not
15,0,	at com.orientechnologies.orient.core.sql.executor.UpdateEdgePointersStep$1.next(UpdateEdgePointersStep.java:35),Not
16,0,	at com.orientechnologies.orient.core.sql.executor.SaveElementStep$1.next(SaveElementStep.java:37),Not
17,0,	at com.orientechnologies.orient.core.sql.executor.CountStep.syncPull(CountStep.java:53),Not
18,0,	at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:37),Not
19,0,	at com.orientechnologies.orient.core.sql.executor.OUpdateExecutionPlan.executeInternal(OUpdateExecutionPlan.java:46),Not
20,0,	at com.orientechnologies.orient.core.sql.parser.OUpdateStatement.execute(OUpdateStatement.java:144),Not
21,0,	at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:59),Not
22,0,	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:540),Not
23,0,	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:175),Not
24,0,	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:84),Not
25,0,	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:36),Not
26,0,	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:172),Not
27,0,	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:633),Not
28,0,	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82),Not
29,0,Internal server error:,NL
31,0,com.orientechnologies.orient.core.exception.OCommandExecutionException: Error updating edge: 'out' is not a vertex - [V#9:0{name:a} v1],Not
32,0,"	DB name=""""test""""",Not
33,0,	at com.orientechnologies.orient.core.sql.executor.UpdateEdgePointersStep.validateOutInForEdge(UpdateEdgePointersStep.java:126),Not
34,0,	at com.orientechnologies.orient.core.sql.executor.UpdateEdgePointersStep.handleUpdateEdge(UpdateEdgePointersStep.java:86),Not
35,0,	at com.orientechnologies.orient.core.sql.executor.UpdateEdgePointersStep.access$000(UpdateEdgePointersStep.java:16),Not
36,0,	at com.orientechnologies.orient.core.sql.executor.UpdateEdgePointersStep$1.next(UpdateEdgePointersStep.java:35),Not
37,0,	at com.orientechnologies.orient.core.sql.executor.SaveElementStep$1.next(SaveElementStep.java:37),Not
38,0,	at com.orientechnologies.orient.core.sql.executor.CountStep.syncPull(CountStep.java:53),Not
39,0,	at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:37),Not
40,0,	at com.orientechnologies.orient.core.sql.executor.OUpdateExecutionPlan.executeInternal(OUpdateExecutionPlan.java:46),Not
41,0,	at com.orientechnologies.orient.core.sql.parser.OUpdateStatement.execute(OUpdateStatement.java:144),Not
42,0,	at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:59),Not
43,0,	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:540),Not
44,0,	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:175),Not
45,0,	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:84),Not
46,0,	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:36),Not
47,0,	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:172),Not
48,0,	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:633)`,Not
50,1,## Steps to reproduce,NL
51,0,`create vertex v set name = 'a'; --> #9:0`,Not
52,0,`create vertex v set name = 'b'; --> #10:0`,Not
53,0,`create vertex v set name = 'c'; --> #11:0`,Not
55,0,`create edge  e  from #10:0 to #11:0; --> #17:0`,NL
57,0,`update edge e set out = (select from v where name = 'a' ) where  @rid = #17:0`,Not
0,1,Looks like query strings are missing from the models and all consumers and providers.,NL
0,1,If enable jackOptions and add some relations to entities app it was crashed during build,NL
2,0,`Caused by: java.lang.NullPointerException,Not
3,0,at io.requery.processor.Mirrors.namesEqual(Mirrors.java:159),Not
4,0,at io.requery.processor.Mirrors.implementsInterface(Mirrors.java:109),Not
5,0,at io.requery.processor.Mirrors.isInstance(Mirrors.java:91),Not
6,0,at io.requery.processor.AttributeMember.validateCollectionType(AttributeMember.java:202),Not
7,0,at io.requery.processor.AttributeMember.checkMemberType(AttributeMember.java:194),Not
8,0,at io.requery.processor.AttributeMember.process(AttributeMember.java:147),Not
9,0,at io.requery.processor.EntityType.lambda$process$5(EntityType.java:114),Not
10,0,at io.requery.processor.EntityType.process(EntityType.java:114),Not
11,0,at io.requery.processor.EntityProcessor.process(EntityProcessor.java:147),Not
12,0,at com.android.jack.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139),Not
13,0,`,Not
0,1,"When using the `createEventConsumer()` or `createTelementryConsumer()`methods on a `HonoClient`, the given `creationHandler` param should fail if the """"attach"""" on the link fails (i.e. """"detach"""" was received).",NL
0,1,**Input file: `Test.java`**,Not
2,0,``` java,Not
3,0,public class Test {,Not
4,0,public static void main(String... args) {,Not
5,0,},Not
6,0,},Not
7,0,```,Not
9,1,**Configuration file: `my_check.xml`**,Not
11,0,``` xml,Not
12,0,"<?xml version=""""1.0""""?>",Not
13,0,<!DOCTYPE module PUBLIC,Not
14,0,"          """"-//Puppy Crawl//DTD Check Configuration 1.3//EN""""",Not
15,0,"          """"http://www.puppycrawl.com/dtds/configuration_1_3.dtd"""">",Not
16,0,"<module name = """"Checker"""">",NL
17,0,"    <property name=""""charset"""" value=""""UTF-8""""/>",Not
18,0,"    <property name=""""severity"""" value=""""warning""""/>",Not
19,0,"    <module name=""""TreeWalker"""">",Not
20,0,"       <module name=""""UncommentedMain""""/>",Not
21,0,</module>,Not
22,0,</module>,Not
25,1,**Checkstyle 6.12.1 output**,Not
27,0,```,Not
28,0,andreiselkin@andreiselkin ~/Downloads/temp $ java -jar checkstyle-6.12.1-all.jar -c my_check.xml Test.java,Not
29,0,Starting audit...,NL
30,0,Audit done.,NL
31,0,```,Not
0,1,**Observations**,Not
1,1,- ES version 2.2.1,Not
2,1,"- If number of documents indexed is 2 , there is no error or issue",NL
3,1,"- With following recreation , I am seeing array_index_out_of_bounds_exception exception ",NL
5,0,```,Not
6,0,curl -XDELETE 'http://localhost:9200/vm/',Not
7,0,echo,NL
8,0,"curl -XPOST 'http://localhost:9200/vm/vm' -d '{ """"name"""" : """"vm"""" , """"rank"""" : 2 , """"date"""" : 2000 }'",Not
9,0,echo,NL
10,0,"curl -XPOST 'http://localhost:9200/vm/vm' -d '{ """"name"""" : """"vm1"""" , """"rank"""" : 2 , """"date"""" : 2000 }'",Not
11,0,echo,NL
12,0,"curl -XPOST 'http://localhost:9200/vm/vm' -d '{ """"name"""" : """"vm2"""" , """"rank"""" : 2 , """"date"""" : 2000 }'",Not
13,0,echo,NL
14,0,"curl -XPOST 'http://localhost:9200/vm/vm' -d '{ """"name"""" : """"vm3"""" , """"rank"""" : 2 , """"date"""" : 2000 }'",Not
15,0,echo,NL
16,0,"curl -XPOST 'http://localhost:9200/vm/vm' -d '{ """"name"""" : """"vm4"""" , """"rank"""" : 2 , """"date"""" : 2000 }'",Not
17,0,echo,NL
18,0,"curl -XPOST 'http://localhost:9200/vm/vm' -d '{ """"name"""" : """"vm5"""" , """"rank"""" : 2 , """"date"""" : 2000 }'",Not
19,0,echo,NL
20,0,"curl -XPOST 'http://localhost:9200/vm/vm' -d '{ """"name"""" : """"vm6"""" , """"rank"""" : 2 , """"date"""" : 2000 }'",Not
21,0,echo,NL
22,0,"curl -XPOST 'http://localhost:9200/vm/vm' -d '{ """"name"""" : """"vm7"""" , """"rank"""" : 2 , """"date"""" : 2000 }'",Not
23,0,echo,NL
24,0,"curl -XPOST 'http://localhost:9200/vm/vm' -d '{ """"name"""" : """"vm8"""" , """"rank"""" : 2 , """"date"""" : 2000 }'",Not
25,0,echo,NL
26,0,"curl -XPOST 'http://localhost:9200/vm/vm' -d '{ """"name"""" : """"vm9"""" , """"rank"""" : 2 , """"date"""" : 2000 }'",Not
27,0,echo,NL
28,0,"curl -XPOST 'http://localhost:9200/vm/vm' -d '{ """"name"""" : """"vm10"""" , """"rank"""" : 2 , """"date"""" : 2000 }'",Not
29,0,echo,NL
30,0,"curl -XPOST 'http://localhost:9200/vm/vm' -d '{ """"name"""" : """"vm11"""" , """"rank"""" : 2 , """"date"""" : 2000 }'",Not
31,0,echo,NL
32,0,curl -XPOST 'http://localhost:9200/vm/_refresh',Not
33,0,echo,NL
34,0,curl -XPOST 'http://localhost:9200/vm/vm/_search?pretty' -d '{,Not
35,0,"  """"size"""": 0,",Not
36,0,"  """"aggs"""": {",Not
37,0,"    """"keywords"""": {",Not
38,0,"      """"terms"""": {",Not
39,0,"        """"collect_mode"""": """"breadth_first"""",",Not
40,0,"        """"field"""": """"name"""",",Not
41,0,"        """"size"""": 1,",Not
42,0,"        """"order"""": {",Not
43,0,"          """"dateB>rankAvg"""": """"asc""""",Not
44,0,},Not
45,0,"      },",NL
46,0,"      """"aggs"""": {",Not
47,0,"        """"dateB"""": {",Not
48,0,"          """"filter"""": {",Not
49,0,"            """"term"""": {",Not
50,0,"              """"date"""": 2001",Not
51,0,},Not
52,0,"          },",Not
53,0,"          """"aggs"""": {",Not
54,0,"            """"rankAvg"""": {",Not
55,0,"              """"min"""": {",Not
56,0,"                """"field"""": """"rank"""",",Not
57,0,"                """"missing"""": 1000",Not
58,0,},Not
59,0,},Not
60,0,},Not
61,0,},Not
62,0,},Not
63,0,},Not
64,0,},Not
65,0,}',Not
66,0,```,Not
68,1,Response,NL
70,0,```,Not
71,0,{,Not
72,0,"  """"took"""" : 13,",Not
73,0,"  """"timed_out"""" : false,",NL
74,0,"  """"_shards"""" : {",Not
75,0,"    """"total"""" : 5,",NL
76,0,"    """"successful"""" : 3,",NL
77,0,"    """"failed"""" : 2,",NL
78,0,"    """"failures"""" : [ {",Not
79,0,"      """"shard"""" : 2,",Not
80,0,"      """"index"""" : """"vm"""",",Not
81,0,"      """"node"""" : """"xpPiHlvJQjSgYu-L10WJuA"""",",Not
82,0,"      """"reason"""" : {",Not
83,0,"        """"type"""" : """"array_index_out_of_bounds_exception"""",",Not
84,0,"        """"reason"""" : """"1""""",Not
85,0,},Not
86,0,} ],Not
87,0,"  },",Not
88,0,"  """"hits"""" : {",Not
89,0,"    """"total"""" : 2,",NL
90,0,"    """"max_score"""" : 0.0,",Not
91,0,"    """"hits"""" : [ ]",Not
92,0,"  },",Not
93,0,"  """"aggregations"""" : {",Not
94,0,"    """"keywords"""" : {",Not
95,0,"      """"doc_count_error_upper_bound"""" : 0,",Not
96,0,"      """"sum_other_doc_count"""" : 1,",Not
97,0,"      """"buckets"""" : [ {",Not
98,0,"        """"key"""" : """"vm10"""",",Not
99,0,"        """"doc_count"""" : 1,",Not
100,0,"        """"dateB"""" : {",Not
101,0,"          """"doc_count"""" : 0,",Not
102,0,"          """"rankAvg"""" : {",Not
103,0,"            """"value"""" : null",Not
104,0,},Not
105,0,},Not
106,0,} ],Not
107,0,},Not
108,0,},Not
109,0,},Not
110,0,```,Not
112,1,Logs emitted,NL
114,0,```,Not
115,0,"[2016-03-21 21:53:55,238][DEBUG][action.search.type       ] [Gertrude Yorkes] [vm][4], node[pkRBZKPTStiOaYYr4mH_-w], [P], v[2], s[STARTED], a[id=Tf6t7fTWRz-FSvU30ln-mA]: Failed to execute [org.elasticsearch.action.search.SearchRequest@a062c99] lastShard [true]",Not
116,0,RemoteTransportException[[Gertrude Yorkes][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: ArrayIndexOutOfBoundsException[1];,Not
117,0,Caused by: java.lang.ArrayIndexOutOfBoundsException: 1,Not
118,0,at org.elasticsearch.common.util.BigArrays$DoubleArrayWrapper.get(BigArrays.java:260),Not
119,0,at org.elasticsearch.search.aggregations.metrics.min.MinAggregator.metric(MinAggregator.java:100),Not
120,0,at org.elasticsearch.search.aggregations.bucket.terms.InternalOrder$Aggregation$3.compare(InternalOrder.java:213),Not
121,0,at org.elasticsearch.search.aggregations.bucket.terms.InternalOrder$Aggregation$3.compare(InternalOrder.java:210),Not
122,0,at org.elasticsearch.search.aggregations.bucket.terms.InternalOrder$CompoundOrder$CompoundOrderComparator.compare(InternalOrder.java:280),Not
123,0,at org.elasticsearch.search.aggregations.bucket.terms.InternalOrder$CompoundOrder$CompoundOrderComparator.compare(InternalOrder.java:266),Not
124,0,at org.elasticsearch.search.aggregations.bucket.terms.support.BucketPriorityQueue.lessThan(BucketPriorityQueue.java:37),Not
125,0,at org.elasticsearch.search.aggregations.bucket.terms.support.BucketPriorityQueue.lessThan(BucketPriorityQueue.java:26),Not
126,0,at org.apache.lucene.util.PriorityQueue.upHeap(PriorityQueue.java:258),Not
127,0,at org.apache.lucene.util.PriorityQueue.add(PriorityQueue.java:135),Not
128,0,at org.apache.lucene.util.PriorityQueue.insertWithOverflow(PriorityQueue.java:151),Not
129,0,at org.elasticsearch.search.aggregations.bucket.terms.GlobalOrdinalsStringTermsAggregator.buildAggregation(GlobalOrdinalsStringTermsAggregator.java:176),Not
130,0,at org.elasticsearch.search.aggregations.AggregationPhase.execute(AggregationPhase.java:167),Not
131,0,at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:119),Not
132,0,at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:364),Not
133,0,at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:376),Not
134,0,at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368),Not
135,0,at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365),Not
136,0,at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350),Not
137,0,at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37),Not
138,0,at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142),Not
139,0,at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617),Not
140,0,at java.lang.Thread.run(Thread.java:745),Not
142,0,```,Not
0,1,"Please provide the following information. The more we know about your system and use case, the more easily and likely we can help.",NL
2,1,### Description of the problem / feature request / question:,NL
3,1,Building Bazel from scratch failed.,NL
5,1,"### If possible, provide a minimal example to reproduce the problem:",NL
6,0,set PATH=C:\msys64\usr\bin;C:\jdk\bin;C:\python35;C:\python35\scripts;%PATH%,Not
7,0,set BAZEL_SH=C:/msys64/usr/bin/bash.exe,Not
8,0,set JAVA_HOME=C:\jdk,Not
9,0,set BAZEL_PYTHON=C:/python35/python.exe,Not
10,0,set BAZEL_VS=C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise,Not
11,0,set JAVA_HOME=C:\jdk,Not
12,0,bash compile.sh,NL
14,1,### Environment info,NL
15,1,* Operating System:,NL
16,1,Windows 10,NL
18,1,* Bazel version (output of `bazel info release`):,NL
19,1,0.6.1,Not
22,1,###  Have you found anything relevant by searching the web?,NL
23,1,None,NL
25,1,"### Anything else, information or logs or outputs that would be helpful?",NL
26,1,Build log:,NL
27,0,```,Not
28,0,Building Bazel from scratch......**********************************************************************,Not
29,0,** Visual Studio 2017 Developer Command Prompt v15.4.0,NL
30,0,** Copyright (c) 2017 Microsoft Corporation,Not
31,0,**********************************************************************,Not
32,0,[vcvarsall.bat] Environment initialized for: 'x64',NL
33,0,Microsoft (R) C/C++ Optimizing Compiler Version 19.11.25547 for x64,NL
34,0,Copyright (C) Microsoft Corporation.  All rights reserved.,NL
36,0,file-jni.cc,Not
37,0,D:\os\bazel-0.6.1-dist\src\main\native\windows\file-jni.cc(25): fatal error C1083: Cannot open include file: 'src/main/native/windows/file.h': No such file or directory,Not
38,0,file.cc,Not
39,0,D:\os\bazel-0.6.1-dist\src\main\native\windows\file.cc(21): fatal error C1083: Cannot open include file: 'src/main/native/windows/file.h': No such file or directory,Not
40,0,jni-util.cc,Not
41,0,D:\os\bazel-0.6.1-dist\src\main\native\windows\jni-util.cc(20): fatal error C1083: Cannot open include file: 'src/main/native/windows/jni-util.h': No such file or directory,Not
42,0,processes-jni.cc,Not
43,0,D:\os\bazel-0.6.1-dist\src\main\native\windows\processes-jni.cc(26): fatal error C1083: Cannot open include file: 'src/main/native/windows/jni-util.h': No such file or directory,Not
44,0,util.cc,Not
45,0,D:\os\bazel-0.6.1-dist\src\main\native\windows\util.cc(24): fatal error C1083: Cannot open include file: 'src/main/native/windows/util.h': No such file or directory,Not
46,0,Generating Code...,NL
47,0,```,Not
49,1,"The content of generated """"windows_jni.bat"""" is something like:",NL
50,0,```bat,Not
51,0,@echo OFF,NL
52,0,"@call """"C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Auxiliary/Build/VCVARSALL.BAT"""" amd64",Not
53,0,@cd D:\os\bazel-0.6.1-dist,Not
54,0,@set TMP=D:\aaa,Not
55,0,@CL /O2 /EHsc /LD /Fe,Not
56,0,```,Not
57,1,"However, after invoking """"VCVARSALL.BAT"""", current working directory would be under C:\xxxx, so """"cd D:\xxxxx"""" doesn't take effect immediately.  you need to call """"D:"""" after that.",NL
0,1,1. Open an image,NL
1,1,2. Open menu,NL
2,1,3. Click Send/Share,NL
3,1,4. :boom:,NL
5,1,All works as expected if I click on the share icon in the file list next to the same image.,NL
0,1,### Issue description,Not
1,1,"I am calling player.getCurrentPosition() to store current position before onPause() is called. However, it sometimes returns 0 (when the video is paused) so the player starts from the beginning when the app resumes.",NL
4,1,### Reproduction steps,Not
5,1,1. Seek to somewhere in the middle of the video. (I am testing HLS streaming),NL
6,1,2. Pause the video,NL
7,1,"3. Press power to turn off the screen and then turn on the screen to resume back to the app. At onPause(),  player.getCurrentPosition() gets called.",NL
8,1,"4. Repeat step 3, until player.getCurrentPosition() returns 0 onPause().",NL
10,1,### Version of ExoPlayer being used,NL
11,1,ExoPlayer version: 2.3.1,Not
13,1,### Device(s) and version(s) of Android being used,NL
14,1,Multiple devices,NL
0,1,We should add basic class condition and at least a check on the application type there.,NL
0,1,The logs show,NL
2,0,```,Not
3,0,/worker-10.233.78.201-2-client/worker.log,Not
4,0,"INFO  2014-09-15 14:38:07,554 [Thread-0] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Initializing test expir ---------------------------",Not
5,0,id=expir,Not
6,0,"INFO  2014-09-15 14:38:08,720 [Thread-2] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Starting expir.setup() ------------------------------------",Not
7,0,"INFO  2014-09-15 14:38:08,813 [Thread-2] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Finished expir.setup() ---------------------------",Not
8,0,"INFO  2014-09-15 14:38:10,731 [Thread-3] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Starting expir.localWarmup() ------------------------------------",Not
9,0,"INFO  2014-09-15 14:38:10,731 [Thread-3] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Finished expir.localWarmup() ---------------------------",Not
10,0,"INFO  2014-09-15 14:38:13,745 [Thread-4] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Starting expir.run() ------------------------------------",Not
11,0,"FATAL 2014-09-15 14:38:13,782 [Thread-4] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Failed to execute expir.run() ------------------------------------",Not
12,0,"INFO  2014-09-15 14:40:14,915 [Thread-0] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- expir.stop() ------------------------------------",Not
13,0,"INFO  2014-09-15 14:40:24,955 [Thread-5] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Starting expir.localVerify() ------------------------------------",Not
14,0,"INFO  2014-09-15 14:40:24,955 [Thread-5] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Finished expir.localVerify() ---------------------------",Not
15,0,"INFO  2014-09-15 14:40:28,971 [Thread-6] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Starting expir.localTeardown() ------------------------------------",Not
16,0,"INFO  2014-09-15 14:40:28,971 [Thread-6] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Finished expir.localTeardown() ---------------------------",Not
17,0,```,Not
19,0,```,Not
20,0,./worker-10.233.78.201-1-server/worker.log,Not
21,0,"INFO  2014-09-15 14:38:06,938 [Thread-0] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Initializing test expir ---------------------------",Not
22,0,id=expir,Not
23,0,"INFO  2014-09-15 14:38:08,079 [Thread-2] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Starting expir.setup() ------------------------------------",Not
24,0,"INFO  2014-09-15 14:38:08,097 [Thread-2] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Finished expir.setup() ---------------------------",Not
25,0,"INFO  2014-09-15 14:38:10,090 [Thread-3] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Starting expir.localWarmup() ------------------------------------",Not
26,0,"INFO  2014-09-15 14:38:10,090 [Thread-3] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Finished expir.localWarmup() ---------------------------",Not
27,0,"INFO  2014-09-15 14:38:12,098 [Thread-4] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Starting expir.globalWarmup() ------------------------------------",Not
28,0,"INFO  2014-09-15 14:38:12,125 [Thread-4] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Finished expir.globalWarmup() ---------------------------",Not
29,0,"INFO  2014-09-15 14:38:14,108 [Thread-5] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Skipping expir.run(); member is passive ------------------------------------",Not
30,0,"INFO  2014-09-15 14:40:14,281 [Thread-0] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- expir.stop() ------------------------------------",Not
31,0,"INFO  2014-09-15 14:40:17,300 [Thread-6] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Starting expir.globalVerify() ------------------------------------",Not
32,0,"INFO  2014-09-15 14:40:19,312 [Thread-6] com.hazelcast.stabilizer.tests.icache.ExpiryTest: expir: Counter{putExpiry=0, putAsyncExpiry=0, getExpiry=0, getAsyncExpiry=0} from 0 worker Threads",Not
33,0,"INFO  2014-09-15 14:40:19,890 [Thread-6] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Finished expir.globalVerify() ---------------------------",Not
34,0,"INFO  2014-09-15 14:40:24,323 [Thread-7] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Starting expir.localVerify() ------------------------------------",Not
35,0,"INFO  2014-09-15 14:40:24,323 [Thread-7] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Finished expir.localVerify() ---------------------------",Not
36,0,"INFO  2014-09-15 14:40:26,331 [Thread-8] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Starting expir.globalTeardown() ------------------------------------",Not
37,0,"INFO  2014-09-15 14:40:26,331 [Thread-8] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Finished expir.globalTeardown() ---------------------------",Not
38,0,"INFO  2014-09-15 14:40:29,363 [Thread-9] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Starting expir.localTeardown() ------------------------------------",Not
39,0,"INFO  2014-09-15 14:40:29,363 [Thread-9] com.hazelcast.stabilizer.worker.MemberWorker: --------------------------- Finished expir.localTeardown() ---------------------------",Not
40,0,```,Not
42,0,```,Not
43,0,"INFO  2014-09-15 14:40:19,312 [Thread-6] com.hazelcast.stabilizer.tests.icache.ExpiryTest: expir: Counter{putExpiry=0, putAsyncExpiry=0, getExpiry=0, getAsyncExpiry=0} from 0 worker Threads",Not
44,0,```,Not
46,1,While Stabilizer shows,NL
48,0,```,Not
49,0,INFO  14:38:06 Running time per test: 00d 00h 02m 00s,NL
50,0,INFO  14:38:06 Expected total testsuite time: 00d 00h 02m 00s,NL
51,0,INFO  14:38:06 Running 1 tests parallel,Not
52,0,INFO  14:38:06 --------------------------------------------------------------,Not
53,0,Running Test : expir,NL
54,0,TestCase{,Not
55,0,id=expir,Not
56,0,"    , class=com.hazelcast.stabilizer.tests.icache.ExpiryTest",Not
57,0,},Not
58,0,--------------------------------------------------------------,Not
59,0,INFO  14:38:06 expir expir Starting Test initialization,Not
60,0,INFO  14:38:07 expir Completed Test initialization,Not
61,0,INFO  14:38:07 expir Starting Test setup,Not
62,0,INFO  14:38:09 expir Completed Test setup,Not
63,0,INFO  14:38:09 expir Starting Test local warmup,Not
64,0,INFO  14:38:11 expir Completed Test local warmup,Not
65,0,INFO  14:38:11 expir Starting Test global warmup,Not
66,0,INFO  14:38:13 expir Completed Test global warmup,Not
67,0,INFO  14:38:13 expir Starting Test start,Not
68,0,INFO  14:38:14 expir Completed Test start,Not
69,0,INFO  14:38:14 expir Test will run for 00d 00h 02m 00s,NL
70,0,"INFO  14:38:44 expir Running 00d 00h 00m 30s, 25.00 percent complete",NL
71,0,"INFO  14:39:14 expir Running 00d 00h 01m 00s, 50.00 percent complete",NL
72,0,"INFO  14:39:44 expir Running 00d 00h 01m 30s, 75.00 percent complete",NL
73,0,"INFO  14:40:14 expir Running 00d 00h 02m 00s, 100.00 percent complete",NL
74,0,INFO  14:40:14 expir Test finished running,Not
75,0,INFO  14:40:14 expir Starting Test stop,Not
76,0,INFO  14:40:16 expir Completed Test stop,Not
77,0,INFO  14:40:17 expir Starting Test global verify,Not
78,0,INFO  14:40:18 expir Waiting for globalVerify completion: 00d 00h 00m 01s,NL
79,0,INFO  14:40:24 expir Completed Test global verify,Not
80,0,INFO  14:40:24 expir Starting Test local verify,Not
81,0,INFO  14:40:26 expir Completed Test local verify,Not
82,0,INFO  14:40:26 expir Starting Test global tear down,NL
83,0,INFO  14:40:27 expir Finished Test global tear down,NL
84,0,INFO  14:40:27 expir Starting Test local tear down,NL
85,0,INFO  14:40:29 expir Completed Test local tear down,NL
86,0,INFO  14:40:29 Terminating workers,Not
87,0,INFO  14:40:29 All workers have been terminated,NL
88,0,INFO  14:40:29 Starting cool down (10 sec),Not
89,0,INFO  14:40:39 Finished cool down,NL
90,0,INFO  14:40:39 Total running time: 152 seconds,Not
91,0,INFO  14:40:39 -----------------------------------------------------------------------------,Not
92,0,INFO  14:40:39 No failures have been detected!,NL
93,0,INFO  14:40:39 -----------------------------------------------------------------------------,Not
94,0,```,Not
0,1,"its actually the same issue as https://github.com/spring-projects/spring-boot/issues/5271, I think the fix didn't work.",NL
1,1,`Log4J2LoggingSystem` installs a filter that denies all and removes it in `Log4J2LoggingSystem#initialize` that is invoked in `ApplicationEnvironmentPreparedEvent`. but if an exception is raised during the preparation of the environment then the filter is not removed yet and the exception is lost. i got it when i had an exception in an `EnvironmentPostProcessor`.,NL
2,1,you can run `sample.actuator.log4j2.SampleActuatorLog4J2Application` with this `application.yml` under resources.,NL
4,0,```yml,Not
5,0,---,Not
6,0,spring:,NL
7,0,profiles:,NL
8,0,active: local,NL
10,0,---,Not
11,0,spring:,NL
12,0,profiles: local,NL
13,0,a=test,Not
14,0,```,Not
16,1,but change the code of `sample.actuator.log4j2.SampleActuatorLog4J2Application` to look like that:,NL
17,0,```java,Not
18,0,try {,Not
19,0,"	SpringApplication.run(SampleActuatorLog4J2Application.class, args);",Not
20,0,}catch (Throwable e){,Not
21,0,"	LoggerFactory.getLogger(SampleActuatorLog4J2Application.class).error(""""error """",e);",Not
22,0,},Not
23,0,```,Not
25,1,"this is actually how our code looks like, we don't always have a main class, we initialize contexts in various ways.",NL
26,1,the exception is not logged.,NL
27,1,only if i remove the filter the exception is logged:,NL
29,0,```java,Not
30,0,try {,Not
31,0,"	SpringApplication.run(SampleActuatorLog4J2Application.class, args);",Not
32,0,}catch (Throwable e){,Not
33,0,	try {,Not
34,0,		Filter filter = ((LoggerContext) LogManager.getContext(false)).getConfiguration().getFilter();,Not
35,0,		if (filter != null) {,Not
36,0,			((LoggerContext) LogManager.getContext(false)).getConfiguration().removeFilter(filter);,Not
37,0,		},Not
38,0,	}catch (Throwable t){,Not
39,0,	},Not
41,0,"	LoggerFactory.getLogger(SampleActuatorLog4J2Application.class).error(""""error """",e);",Not
42,0,},Not
44,0,```,Not
47,1,Thanks,NL
0,1,"I have a webapp that I've developed with Spring, CXF and Apache Camel. I've been developing it for several months, using Tomcat to run and test it. This week, I integrated Spring Boot to take advantage of its external configuration feature.",NL
2,1,"Now something strange is happening. If I run """"mvn spring-boot:run"""" and run my integration tests against it, everything works fine. The headers on my SOAP requests look as follows:",NL
4,0,```,Not
5,0,HTTP/1.1 200 OK,NL
6,0,Server: Apache-Coyote/1.1,Not
7,0,X-Application-Context: application,Not
8,0,X-Application-Context: application,Not
9,0,Content-Type: application/soap+xml;charset=UTF-8,Not
10,0,Content-Length: 333,Not
11,0,"Date: Wed, 30 Jul 2014 17:03:18 GMT",Not
14,1,"However, if I run the same application in Tomcat, it seems that something is removing the Content-\* headers.",NL
16,0,```,Not
17,0,HTTP/1.1 200 OK,NL
18,0,Server: Apache-Coyote/1.1,Not
19,0,X-Application-Context: application,Not
20,0,Transfer-Encoding: chunked,Not
21,0,"Date: Wed, 30 Jul 2014 17:01:09 GMT",Not
22,0,```,Not
24,1,This all worked fine before I integrated Spring Boot 1.1.4.,NL
0,1,"As I described in the title, I am trying to utilize Key Hash Tags to accumulate data on the same ClusterNode.",NL
1,1,I am using a Multimap and noticed the Key for the Lists/Sets are wrapped in the Key Hash Tags and so they may be placed on another Node.,NL
3,1,For example:,NL
4,1,"The MultiMap key is """"{multi.map}.some.key"""".",NL
5,1,"An entry in it would be saved in the List/Set """"{{multi.map}.some.key}:ADJ..."""".",NL
6,1,"So the Hash is not """"multi.map"""" but rather """"{multi.map"""".",NL
8,1,"For further information see the """"Key Hash Tag"""" section on https://redis.io/topics/cluster-spec",NL
0,1,"TimeBoundary and maxTime queries do not need to access and merge data from every segment in an interval, they only need information from the most and least recent segments.",NL
0,1,### Description of the problem / feature request:,NL
2,1,"I want to use bazel to build a go project using [rules_go](https://github.com/bazelbuild/rules_go), I have some external packages in my `WORKSPACE` file. Some of these packages are in github, golang.org, gopkg.in etc., which can be fetched from internet. The other packages are placed in internal network. However, because I'm in China, for fetching the external internet packages from github, golang.org, gopkg.in, I must set a HTTP_PROXY and HTTPS_PROXY for enjoying a high speed. But for fetching the packages in internal network, I must set NO_PROXY.",NL
4,1,"However, if I set the HTTP_PROXY, HTTPS_PROXY and NO_PROXY and execute `bazel build //...`, the external packages can be fetched but the internal packages cannot be fetched. Seems bazel doesn't respect NO_PROXY. I use `htop` and find that bazel will hang in ",NL
6,0,```,Not
7,0,/cache/dfb1ce1d07f3a35961571a3241719bc6/external/bazel_gazelle_go_repository_tools/bin/fetch_repo --dest /cache/dfb1ce1d07f3a35961571a3241719bc6/external/<internal_package_name> --rev 84535ec2d57a694b372ec5effa446098b2c2202f --importpath <internal_package_address>,Not
8,0,```,Not
10,1,"The interesting thing is that if I execute the command above directly in the terminal, it can be successfully executed and fetch the packages in the relative directory.",NL
12,1,"And if I unset HTTP_PROXY and HTTPS_PROXY, I can successfully fetch the internal packages by using bazel.",NL
14,1,### Feature requests: what underlying problem are you trying to solve with this feature?,NL
16,1,"I notice that while I set HTTP_PROXY, bazel will show a log about ",NL
18,0,```,Not
19,0,"WARNING: detected http_proxy set in env, setting no_proxy for localhost.",NL
20,0,```,Not
22,1,"I try to find it in the [sources](https://github.com/bazelbuild/bazel/blob/master/src/main/cpp/blaze.cc#L1425) and discover that it seems bazel will set NO_PROXY directly to `localhost,127.0.0.1,0:0:0:0:0:0:0:1,::1` regardless of the origin value of NO_PROXY while HTTP_PROXY exists. Than I change the code to make it respects the origin value of NO_PROXY and use bazel to build it.",NL
24,1,"However, using the bazel built by myself, it also not worked for me to respect NO_PROXY. It cannot fetch the internal packages yet. I also try to reference https://github.com/bazelbuild/bazel/pull/4307 and https://github.com/bazelbuild/bazel/issues/4299, but it seems not a solution for my problem.",NL
26,1,### What operating system are you running Bazel on?,NL
28,1,"I use bazel 0.17.2 in ubuntu 18.04 and 16.04, both have the same bug",NL
30,1,### What's the output of `bazel info release`?,NL
32,1,`release 0.17.2`,Not
34,1,"### If `bazel info release` returns """"development version"""" or """"(@non-git)"""", tell us how you built Bazel.",NL
36,1,"I try to change code like [this](https://github.com/weixiao-huang/bazel/commit/2269036e434a7177782e06590eee8495a08080e1), and use bazel to rebuild bazel",NL
38,0,```,Not
39,0,bazel build //src:bazel,Not
40,0,```,Not
42,1,but the problem still exists.,NL
44,1,###  Have you found anything relevant by searching the web?,NL
46,1,"I just find some issues in bazel's git, but it seems that they have few helps for my problem",NL
48,1,- https://github.com/bazelbuild/bazel/pull/4307,Not
49,1,- https://github.com/bazelbuild/bazel/issues/4299,Not
0,1,"During repository verification the master node writes a single test file into repository and then all data nodes try to read this file back. If this operation fails, the error message `store location [......] is not shared between node [the data node name] and the master node]`. The message can be very confusing in situation when there is only one node in the cluster and the error is caused by wrong S3 permissions. ",NL
0,1,Address like `192.168.234.129:7001@17001` should be converted to `192.168.234.129:7001`,NL
0,1,Kotlin static interface fields cause `NotNull not applicable to static or final member` error.,NL
2,0,```,Not
3,0,@Entity,NL
4,0,"interface Thing : Persistable, Observable, Parcelable {",Not
5,0,@get:Key @get:Generated,Not
6,0,var id : Int,NL
8,0,companion object {,Not
9,0,"        const val THING_CONSTANT = """"something""""",Not
10,0,},Not
11,0,},Not
12,0,```,Not
14,1,I haven't tried with Java.,NL
0,1,"For asynchronous tests, the expected start-time isn't available. So asynchronous tests can only make use of actual start-time, reintroducing the coordinated omission problem.",NL
2,1,So it should be possible to expose the intended start-time as argument.,NL
0,1,"Hey,",NL
2,1,When I set `setPingConnectionInterval` in the replicated servers configuration it's not propagated to underlying master slave configuration:,NL
4,0,```,Not
5,0,config.useReplicatedServers(),Not
6,0,.setPingConnectionInterval(1000),Not
7,0,.addNodeAddress(nodeAddresses.toArray(new String[0]));,Not
8,0,```,Not
10,1,My current understand that ReplicatedServersConfig is used to create MasterSlaveServersConfiguration In the MasterSlaveConnectionManager in https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/connection/MasterSlaveConnectionManager.java#L389.,NL
12,1,In this method setPingConnectionInterval is not copied and default value is used in MasterSlaveServersConfiguration.,NL
0,1,"Using Netty on a Java-VM running on IBM z/OS it occurs, that creating a unique channel-id leads to problems.",NL
1,1,"It seems to me, that this process bases at least on the MAC-Address of networking hardware.  On IBM z/OS this information is not available with the usual JAVA-methods in NetworkInterface.  Netty logs always a warning to System.err running on z/OS that it fell back to a random MAC.",NL
2,1,So I decided to use the VM-Option io.netty.machineId=xxxxxxxx to inject here a valid MAC-Address retrieved from non-java resources on z/OS.,NL
4,1,"**To my regrets it does not work. The problem is not platform-dependent, even with in a SUN-VM running on Windows it is not possible to use this option.** ",NL
6,1,"Probably the Regular Expression, used to check the input, is not correct.",NL
7,1,I would recommend to change the used RegExp,NL
8,0,"` private static final Pattern MACHINE_ID_PATTERN = Pattern.compile(""""^(?:[0-9a-fA-F][:-]?){6,8}$"""");`",Not
9,1,to an expression more like,NL
10,0,"`([0-9a-fA-F]{2}[:-]){5,7}[0-9a-fA-F]{2}`",Not
13,1,### Expected behavior,Not
14,1,DefaultChannelId allows to customize the used MACAddress via System.property.,NL
15,1,Using -Dio.netty.machineId=00-14-5E-5A-AF-77 as Java-VM-option should be accepted as valid MACAddress.,NL
17,1,### Actual behavior,Not
18,1,Netty rejects this MACAddress as malformed:,NL
20,0,"`Dez 14, 2016 2:10:49 PM io.netty.channel.DefaultChannelId <clinit>",Not
21,0,WARNING: -Dio.netty.machineId: 00-14-5E-5A-AF-77 (malformed),Not
22,0,"Dez 14, 2016 2:10:49 PM io.netty.handler.logging.LoggingHandler channelRegistered",Not
23,0,INFO: [id: 0xa9354b7b] REGISTERED,Not
24,0,"Dez 14, 2016 2:10:49 PM io.netty.handler.logging.LoggingHandler bind",Not
25,0,INFO: [id: 0xa9354b7b] BIND: 0.0.0.0/0.0.0.0:8007,Not
26,0,"Dez 14, 2016 2:10:49 PM io.netty.handler.logging.LoggingHandler channelActive",Not
27,0,"INFO: [id: 0xa9354b7b, L:/0:0:0:0:0:0:0:0:8007] ACTIVE`",Not
29,1,### Steps to reproduce,NL
30,1,"Start any Netty-using application (i.e. your sample io.netty.example.echo.EchoServer) with VM-option -Dio.netty.machineId=xxxxxxxx to overrule the standard MAC-Address ascertaining in MacAddressUtil.bestAvailableMac(), where xxxxxxx is any MAC-Address in standard (IEEE 802) format for printing MAC-48 addresses in human-friendly form.",NL
32,1,### Minimal yet complete reproducer code (or URL to code),Not
33,1,see above. Reproducible via VM-option,NL
35,1,### Netty version,Not
36,1,4.1.5,Not
38,1,### JVM version (e.g. `java -version`),Not
39,1,"java version """"1.8.0_111""""",Not
40,1,Java(TM) SE Runtime Environment (build 1.8.0_111-b14),Not
41,1,"Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)",Not
43,1,### OS version (e.g. `uname -a`),Not
44,1,Windows 7 Professional Service Pack 1,NL
0,1,`RqLengthAware` gives wrong information at `available()` call,NL
0,1,We miss to notify the ChannelFuture of the pendingWrite which is just in progress if the SSLEngine was closed. This means the the ChannelFutureListener will never get notifived in that case.,NL
